/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\cnc.glb --types --keepnames --keepgroups --shadows --exportdefault 
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { Box, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    M957I478: THREE.Mesh
    M955I477: THREE.Mesh
    M953I476: THREE.Mesh
    M951I475: THREE.Mesh
    M949I474: THREE.Mesh
    M947I473: THREE.Mesh
    M945I472: THREE.Mesh
    M943I471: THREE.Mesh
    M941I470: THREE.Mesh
    M939I469: THREE.Mesh
    M937I468: THREE.Mesh
    M935I467: THREE.Mesh
    M933I466: THREE.Mesh
    M931I465: THREE.Mesh
    M929I464: THREE.Mesh
    M927I463: THREE.Mesh
    M925I462: THREE.Mesh
    M923I461: THREE.Mesh
    M921I460: THREE.Mesh
    M919I459: THREE.Mesh
    M917I458: THREE.Mesh
    M915I457: THREE.Mesh
    M913I456: THREE.Mesh
    M911I455: THREE.Mesh
    M909I454: THREE.Mesh
    M907I453: THREE.Mesh
    M905I452: THREE.Mesh
    M903I451: THREE.Mesh
    M901I450: THREE.Mesh
    M899I449: THREE.Mesh
    M897I448: THREE.Mesh
    M895I447: THREE.Mesh
    M893I446: THREE.Mesh
    M891I445: THREE.Mesh
    M889I444: THREE.Mesh
    M887I443: THREE.Mesh
    M885I442: THREE.Mesh
    M883I441: THREE.Mesh
    M881I440: THREE.Mesh
    M879I439: THREE.Mesh
    M877I438: THREE.Mesh
    M875I437: THREE.Mesh
    M873I436: THREE.Mesh
    M871I435: THREE.Mesh
    M869I434: THREE.Mesh
    M867I433: THREE.Mesh
    M865I432: THREE.Mesh
    M863I431: THREE.Mesh
    M861I430: THREE.Mesh
    M859I429: THREE.Mesh
    M857I428: THREE.Mesh
    M855I427: THREE.Mesh
    M853I426: THREE.Mesh
    M851I425: THREE.Mesh
    M849I424: THREE.Mesh
    M847I423: THREE.Mesh
    M845I422: THREE.Mesh
    M843I421: THREE.Mesh
    M841I420: THREE.Mesh
    M839I419: THREE.Mesh
    M837I418: THREE.Mesh
    M835I417: THREE.Mesh
    M833I416: THREE.Mesh
    M831I415: THREE.Mesh
    M829I414: THREE.Mesh
    M827I413: THREE.Mesh
    M825I412: THREE.Mesh
    M823I411: THREE.Mesh
    M821I410: THREE.Mesh
    M819I409: THREE.Mesh
    M817I408: THREE.Mesh
    M815I407: THREE.Mesh
    M813I406: THREE.Mesh
    M811I405: THREE.Mesh
    M809I404: THREE.Mesh
    M807I403: THREE.Mesh
    M805I402: THREE.Mesh
    M803I401: THREE.Mesh
    M801I400: THREE.Mesh
    M799I399: THREE.Mesh
    M797I398: THREE.Mesh
    M795I397: THREE.Mesh
    M793I396: THREE.Mesh
    M791I395: THREE.Mesh
    M789I394: THREE.Mesh
    M787I393: THREE.Mesh
    M785I392: THREE.Mesh
    M783I391: THREE.Mesh
    M781I390: THREE.Mesh
    M779I389: THREE.Mesh
    M777I388: THREE.Mesh
    M775I387: THREE.Mesh
    M773I386: THREE.Mesh
    M771I385: THREE.Mesh
    M769I384: THREE.Mesh
    M767I383: THREE.Mesh
    M765I382: THREE.Mesh
    M763I381: THREE.Mesh
    M761I380: THREE.Mesh
    M759I379: THREE.Mesh
    M757I378: THREE.Mesh
    M755I377: THREE.Mesh
    M753I376: THREE.Mesh
    M751I375: THREE.Mesh
    M749I374: THREE.Mesh
    M747I373: THREE.Mesh
    M745I372: THREE.Mesh
    M743I371: THREE.Mesh
    M741I370: THREE.Mesh
    M739I369: THREE.Mesh
    M737I368: THREE.Mesh
    M735I367: THREE.Mesh
    M733I366: THREE.Mesh
    M731I365: THREE.Mesh
    M729I364: THREE.Mesh
    M727I363: THREE.Mesh
    M725I362: THREE.Mesh
    M723I361: THREE.Mesh
    M721I360: THREE.Mesh
    M719I359: THREE.Mesh
    M717I358: THREE.Mesh
    M715I357: THREE.Mesh
    M713I356: THREE.Mesh
    M711I355: THREE.Mesh
    M709I354: THREE.Mesh
    M707I353: THREE.Mesh
    M705I352: THREE.Mesh
    M703I351: THREE.Mesh
    M701I350: THREE.Mesh
    M699I349: THREE.Mesh
    M697I348: THREE.Mesh
    M695I347: THREE.Mesh
    M693I346: THREE.Mesh
    M691I345: THREE.Mesh
    M689I344: THREE.Mesh
    M687I343: THREE.Mesh
    M685I342: THREE.Mesh
    M683I341: THREE.Mesh
    M681I340: THREE.Mesh
    M679I339: THREE.Mesh
    M677I338: THREE.Mesh
    M675I337: THREE.Mesh
    M673I336: THREE.Mesh
    M671I335: THREE.Mesh
    M669I334: THREE.Mesh
    M667I333: THREE.Mesh
    M665I332: THREE.Mesh
    M663I331: THREE.Mesh
    M661I330: THREE.Mesh
    M659I329: THREE.Mesh
    M657I328: THREE.Mesh
    M655I327: THREE.Mesh
    M653I326: THREE.Mesh
    M651I325: THREE.Mesh
    M649I324: THREE.Mesh
    M647I323: THREE.Mesh
    M645I322: THREE.Mesh
    M643I321: THREE.Mesh
    M641I320: THREE.Mesh
    M639I319: THREE.Mesh
    M637I318: THREE.Mesh
    M635I317: THREE.Mesh
    M633I316: THREE.Mesh
    M631I315: THREE.Mesh
    M629I314: THREE.Mesh
    M627I313: THREE.Mesh
    M625I312: THREE.Mesh
    M623I311: THREE.Mesh
    M621I310: THREE.Mesh
    M619I309: THREE.Mesh
    M617I308: THREE.Mesh
    M615I307: THREE.Mesh
    M613I306: THREE.Mesh
    M611I305: THREE.Mesh
    M609I304: THREE.Mesh
    M607I303: THREE.Mesh
    M605I302: THREE.Mesh
    M603I301: THREE.Mesh
    M601I300: THREE.Mesh
    M599I299: THREE.Mesh
    M597I298: THREE.Mesh
    M595I297: THREE.Mesh
    M593I296: THREE.Mesh
    M591I295: THREE.Mesh
    M589I294: THREE.Mesh
    M587I293: THREE.Mesh
    M585I292: THREE.Mesh
    M583I291: THREE.Mesh
    M581I290: THREE.Mesh
    M579I289: THREE.Mesh
    M577I288: THREE.Mesh
    M575I287: THREE.Mesh
    M573I286: THREE.Mesh
    M571I285: THREE.Mesh
    M569I284: THREE.Mesh
    M567I283: THREE.Mesh
    M565I282: THREE.Mesh
    M563I281: THREE.Mesh
    M561I280: THREE.Mesh
    M559I279: THREE.Mesh
    M557I278: THREE.Mesh
    M555I277: THREE.Mesh
    M553I276: THREE.Mesh
    M551I275: THREE.Mesh
    M549I274: THREE.Mesh
    M547I273: THREE.Mesh
    M545I272: THREE.Mesh
    M543I271: THREE.Mesh
    M541I270: THREE.Mesh
    M539I269: THREE.Mesh
    M537I268: THREE.Mesh
    M535I267: THREE.Mesh
    M533I266: THREE.Mesh
    M531I265: THREE.Mesh
    M529I264: THREE.Mesh
    M527I263: THREE.Mesh
    M525I262: THREE.Mesh
    M523I261: THREE.Mesh
    M521I260: THREE.Mesh
    M519I259: THREE.Mesh
    M517I258: THREE.Mesh
    M515I257: THREE.Mesh
    M513I256: THREE.Mesh
    M511I255: THREE.Mesh
    M509I254: THREE.Mesh
    M507I253: THREE.Mesh
    M505I252: THREE.Mesh
    M503I251: THREE.Mesh
    M501I250: THREE.Mesh
    M499I249: THREE.Mesh
    M497I248: THREE.Mesh
    M495I247: THREE.Mesh
    M493I246: THREE.Mesh
    M491I245: THREE.Mesh
    M489I244: THREE.Mesh
    M487I243: THREE.Mesh
    M485I242: THREE.Mesh
    M483I241: THREE.Mesh
    M481I240: THREE.Mesh
    M479I239: THREE.Mesh
    M477I238: THREE.Mesh
    M475I237: THREE.Mesh
    M473I236: THREE.Mesh
    M471I235: THREE.Mesh
    M469I234: THREE.Mesh
    M467I233: THREE.Mesh
    M465I232: THREE.Mesh
    M463I231: THREE.Mesh
    M461I230: THREE.Mesh
    M459I229: THREE.Mesh
    M457I228: THREE.Mesh
    M455I227: THREE.Mesh
    M453I226: THREE.Mesh
    M451I225: THREE.Mesh
    M449I224: THREE.Mesh
    M447I223: THREE.Mesh
    M445I222: THREE.Mesh
    M443I221: THREE.Mesh
    M441I220: THREE.Mesh
    M439I219: THREE.Mesh
    M437I218: THREE.Mesh
    M435I217: THREE.Mesh
    M433I216: THREE.Mesh
    M431I215: THREE.Mesh
    M429I214: THREE.Mesh
    M427I213: THREE.Mesh
    M425I212: THREE.Mesh
    M423I211: THREE.Mesh
    M421I210: THREE.Mesh
    M419I209: THREE.Mesh
    M417I208: THREE.Mesh
    M415I207: THREE.Mesh
    M413I206: THREE.Mesh
    M411I205: THREE.Mesh
    M409I204: THREE.Mesh
    M407I203: THREE.Mesh
    M405I202: THREE.Mesh
    M403I201: THREE.Mesh
    M401I200: THREE.Mesh
    M399I199: THREE.Mesh
    M397I198: THREE.Mesh
    M395I197: THREE.Mesh
    M393I196: THREE.Mesh
    M391I195: THREE.Mesh
    M389I194: THREE.Mesh
    M387I193: THREE.Mesh
    M385I192: THREE.Mesh
    M383I191: THREE.Mesh
    M381I190: THREE.Mesh
    M379I189: THREE.Mesh
    M377I188: THREE.Mesh
    M375I187: THREE.Mesh
    M373I186: THREE.Mesh
    M371I185: THREE.Mesh
    M369I184: THREE.Mesh
    M367I183: THREE.Mesh
    M365I182: THREE.Mesh
    M363I181: THREE.Mesh
    M361I180: THREE.Mesh
    M359I179: THREE.Mesh
    M357I178: THREE.Mesh
    M355I177: THREE.Mesh
    M353I176: THREE.Mesh
    M351I175: THREE.Mesh
    M349I174: THREE.Mesh
    M347I173: THREE.Mesh
    M345I172: THREE.Mesh
    M343I171: THREE.Mesh
    M341I170: THREE.Mesh
    M339I169: THREE.Mesh
    M337I168: THREE.Mesh
    M335I167: THREE.Mesh
    M333I166: THREE.Mesh
    M331I165: THREE.Mesh
    M329I164: THREE.Mesh
    M327I163: THREE.Mesh
    M325I162: THREE.Mesh
    M323I161: THREE.Mesh
    M321I160: THREE.Mesh
    M319I159: THREE.Mesh
    M317I158: THREE.Mesh
    M315I157: THREE.Mesh
    M313I156: THREE.Mesh
    M311I155: THREE.Mesh
    M309I154: THREE.Mesh
    M307I153: THREE.Mesh
    M305I152: THREE.Mesh
    M303I151: THREE.Mesh
    M301I150: THREE.Mesh
    M299I149: THREE.Mesh
    M297I148: THREE.Mesh
    M295I147: THREE.Mesh
    M293I146: THREE.Mesh
    M291I145: THREE.Mesh
    M289I144: THREE.Mesh
    M287I143: THREE.Mesh
    M285I142: THREE.Mesh
    M283I141: THREE.Mesh
    M281I140: THREE.Mesh
    M279I139: THREE.Mesh
    M277I138: THREE.Mesh
    M275I137: THREE.Mesh
    M273I136: THREE.Mesh
    M271I135: THREE.Mesh
    M269I134: THREE.Mesh
    M267I133: THREE.Mesh
    M265I132: THREE.Mesh
    M263I131: THREE.Mesh
    M261I130: THREE.Mesh
    M259I129: THREE.Mesh
    M257I128: THREE.Mesh
    M255I127: THREE.Mesh
    M253I126: THREE.Mesh
    M251I125: THREE.Mesh
    M249I124: THREE.Mesh
    M247I123: THREE.Mesh
    M245I122: THREE.Mesh
    M243I121: THREE.Mesh
    M241I120: THREE.Mesh
    M239I119: THREE.Mesh
    M237I118: THREE.Mesh
    M235I117: THREE.Mesh
    M233I116: THREE.Mesh
    M231I115: THREE.Mesh
    M229I114: THREE.Mesh
    M227I113: THREE.Mesh
    M225I112: THREE.Mesh
    M223I111: THREE.Mesh
    M221I110: THREE.Mesh
    M219I109: THREE.Mesh
    M217I108: THREE.Mesh
    M215I107: THREE.Mesh
    M213I106: THREE.Mesh
    M211I105: THREE.Mesh
    M209I104: THREE.Mesh
    M207I103: THREE.Mesh
    M205I102: THREE.Mesh
    M203I101: THREE.Mesh
    M201I100: THREE.Mesh
    M199I99: THREE.Mesh
    M197I98: THREE.Mesh
    M195I97: THREE.Mesh
    M193I96: THREE.Mesh
    M191I95: THREE.Mesh
    M189I94: THREE.Mesh
    M187I93: THREE.Mesh
    M185I92: THREE.Mesh
    M183I91: THREE.Mesh
    M181I90: THREE.Mesh
    M179I89: THREE.Mesh
    M177I88: THREE.Mesh
    M175I87: THREE.Mesh
    M173I86: THREE.Mesh
    M171I85: THREE.Mesh
    M169I84: THREE.Mesh
    M167I83: THREE.Mesh
    M165I82: THREE.Mesh
    M163I81: THREE.Mesh
    M161I80: THREE.Mesh
    M159I79: THREE.Mesh
    M157I78: THREE.Mesh
    M155I77: THREE.Mesh
    M153I76: THREE.Mesh
    M151I75: THREE.Mesh
    M149I74: THREE.Mesh
    M147I73: THREE.Mesh
    M145I72: THREE.Mesh
    M143I71: THREE.Mesh
    M141I70: THREE.Mesh
    M139I69: THREE.Mesh
    M137I68: THREE.Mesh
    M135I67: THREE.Mesh
    M133I66: THREE.Mesh
    M131I65: THREE.Mesh
    M129I64: THREE.Mesh
    M127I63: THREE.Mesh
    M125I62: THREE.Mesh
    M123I61: THREE.Mesh
    M121I60: THREE.Mesh
    M119I59: THREE.Mesh
    M117I58: THREE.Mesh
    M115I57: THREE.Mesh
    M113I56: THREE.Mesh
    M111I55: THREE.Mesh
    M109I54: THREE.Mesh
    M107I53: THREE.Mesh
    M105I52: THREE.Mesh
    M103I51: THREE.Mesh
    M101I50: THREE.Mesh
    M99I49: THREE.Mesh
    M97I48: THREE.Mesh
    M95I47: THREE.Mesh
    M93I46: THREE.Mesh
    M91I45: THREE.Mesh
    M89I44: THREE.Mesh
    M87I43: THREE.Mesh
    M85I42: THREE.Mesh
    M83I41: THREE.Mesh
    M81I40: THREE.Mesh
    M79I39: THREE.Mesh
    M77I38: THREE.Mesh
    M75I37: THREE.Mesh
    M73I36: THREE.Mesh
    M71I35: THREE.Mesh
    M69I34: THREE.Mesh
    M67I33: THREE.Mesh
    M65I32: THREE.Mesh
    M63I31: THREE.Mesh
    M61I30: THREE.Mesh
    M59I29: THREE.Mesh
    M57I28: THREE.Mesh
    M55I27: THREE.Mesh
    M53I26: THREE.Mesh
    M51I25: THREE.Mesh
    M49I24: THREE.Mesh
    M47I23: THREE.Mesh
    M45I22: THREE.Mesh
    M43I21: THREE.Mesh
    M41I20: THREE.Mesh
    M39I19: THREE.Mesh
    M37I18: THREE.Mesh
    M35I17: THREE.Mesh
    M33I16: THREE.Mesh
    M31I15: THREE.Mesh
    M29I14: THREE.Mesh
    M27I13: THREE.Mesh
    M25I12: THREE.Mesh
    M23I11: THREE.Mesh
    M21I10: THREE.Mesh
    M19I9: THREE.Mesh
    M17I8: THREE.Mesh
    M15I7: THREE.Mesh
    M13I6: THREE.Mesh
    M11I5: THREE.Mesh
    M9I4: THREE.Mesh
    M7I3: THREE.Mesh
    M5I2: THREE.Mesh
    M3I1: THREE.Mesh
    M1I0: THREE.Mesh
  }
  materials: {
    COL27: THREE.MeshStandardMaterial
    COL26: THREE.MeshStandardMaterial
    COL25: THREE.MeshStandardMaterial
    COL24: THREE.MeshStandardMaterial
    COL23: THREE.MeshStandardMaterial
    COL22: THREE.MeshStandardMaterial
    COL21: THREE.MeshStandardMaterial
    COL16: THREE.MeshStandardMaterial
    COL1: THREE.MeshStandardMaterial
    COL3: THREE.MeshStandardMaterial
    COL4: THREE.MeshStandardMaterial
    COL7: THREE.MeshStandardMaterial
    COL12: THREE.MeshStandardMaterial
    COL5: THREE.MeshStandardMaterial
    COL2: THREE.MeshStandardMaterial
    COL20: THREE.MeshStandardMaterial
    COL18: THREE.MeshStandardMaterial
    COL11: THREE.MeshStandardMaterial
    COL0: THREE.MeshStandardMaterial
    COL19: THREE.MeshStandardMaterial
    COL17: THREE.MeshStandardMaterial
    COL13: THREE.MeshStandardMaterial
    COL6: THREE.MeshStandardMaterial
    COL10: THREE.MeshStandardMaterial
    COL8: THREE.MeshStandardMaterial
    COL15: THREE.MeshStandardMaterial
    COL14: THREE.MeshStandardMaterial
    COL9: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cnc.glb') as GLTFResult

  const machineRef = React.useRef<THREE.Group>(null)

  useEffect(() => {
    // Replace the materials of all submeshes

    if (machineRef.current) {
      machineRef.current.traverse((child) => {
        if (child instanceof THREE.Mesh) {

          const oldMaterial = child.material as THREE.MeshStandardMaterial
          child.frustumCulled 
          child.material = new THREE.MeshStandardMaterial({
            // color: materials.COL7.color,
            color: oldMaterial.color,
            transparent: true,
            opacity: 0.9,
            roughness: 0.5,
            metalness: 0.5,
            side: THREE.DoubleSide,
          })
        }
      })
    }

  }, [nodes, materials])
  
  return (
    <group {...props} dispose={null} ref={machineRef}>
      <group name="Scene" >
        {/* <Box /> */}
        <mesh name="M957I478" castShadow receiveShadow geometry={nodes.M957I478.geometry} material={materials.COL27} position={[2.047, -0.325, -0.918]} />
        <mesh name="M955I477" castShadow receiveShadow geometry={nodes.M955I477.geometry} material={materials.COL26} position={[2.047, -0.325, -0.918]} />
        <mesh name="M953I476" castShadow receiveShadow geometry={nodes.M953I476.geometry} material={materials.COL25} position={[2.047, -0.325, -0.918]} />
        <mesh name="M951I475" castShadow receiveShadow geometry={nodes.M951I475.geometry} material={materials.COL25} position={[2.047, -0.325, -0.918]} />
        <mesh name="M949I474" castShadow receiveShadow geometry={nodes.M949I474.geometry} material={materials.COL24} position={[2.047, -0.325, -0.918]} />
        <mesh name="M947I473" castShadow receiveShadow geometry={nodes.M947I473.geometry} material={materials.COL23} position={[2.047, -0.325, -0.918]} />
        <mesh name="M945I472" castShadow receiveShadow geometry={nodes.M945I472.geometry} material={materials.COL22} position={[2.047, -0.325, -0.918]} />
        <mesh name="M943I471" castShadow receiveShadow geometry={nodes.M943I471.geometry} material={materials.COL21} position={[2.047, -0.325, -0.918]} />
        <mesh name="M941I470" castShadow receiveShadow geometry={nodes.M941I470.geometry} material={materials.COL16} position={[2.047, -0.325, -0.918]} />
        <mesh name="M939I469" castShadow receiveShadow geometry={nodes.M939I469.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M937I468" castShadow receiveShadow geometry={nodes.M937I468.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M935I467" castShadow receiveShadow geometry={nodes.M935I467.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M933I466" castShadow receiveShadow geometry={nodes.M933I466.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M931I465" castShadow receiveShadow geometry={nodes.M931I465.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M929I464" castShadow receiveShadow geometry={nodes.M929I464.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M927I463" castShadow receiveShadow geometry={nodes.M927I463.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M925I462" castShadow receiveShadow geometry={nodes.M925I462.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M923I461" castShadow receiveShadow geometry={nodes.M923I461.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M921I460" castShadow receiveShadow geometry={nodes.M921I460.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M919I459" castShadow receiveShadow geometry={nodes.M919I459.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M917I458" castShadow receiveShadow geometry={nodes.M917I458.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M915I457" castShadow receiveShadow geometry={nodes.M915I457.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M913I456" castShadow receiveShadow geometry={nodes.M913I456.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M911I455" castShadow receiveShadow geometry={nodes.M911I455.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M909I454" castShadow receiveShadow geometry={nodes.M909I454.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M907I453" castShadow receiveShadow geometry={nodes.M907I453.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M905I452" castShadow receiveShadow geometry={nodes.M905I452.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M903I451" castShadow receiveShadow geometry={nodes.M903I451.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M901I450" castShadow receiveShadow geometry={nodes.M901I450.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M899I449" castShadow receiveShadow geometry={nodes.M899I449.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M897I448" castShadow receiveShadow geometry={nodes.M897I448.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M895I447" castShadow receiveShadow geometry={nodes.M895I447.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M893I446" castShadow receiveShadow geometry={nodes.M893I446.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M891I445" castShadow receiveShadow geometry={nodes.M891I445.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M889I444" castShadow receiveShadow geometry={nodes.M889I444.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M887I443" castShadow receiveShadow geometry={nodes.M887I443.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M885I442" castShadow receiveShadow geometry={nodes.M885I442.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M883I441" castShadow receiveShadow geometry={nodes.M883I441.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M881I440" castShadow receiveShadow geometry={nodes.M881I440.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M879I439" castShadow receiveShadow geometry={nodes.M879I439.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M877I438" castShadow receiveShadow geometry={nodes.M877I438.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M875I437" castShadow receiveShadow geometry={nodes.M875I437.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M873I436" castShadow receiveShadow geometry={nodes.M873I436.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M871I435" castShadow receiveShadow geometry={nodes.M871I435.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M869I434" castShadow receiveShadow geometry={nodes.M869I434.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M867I433" castShadow receiveShadow geometry={nodes.M867I433.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M865I432" castShadow receiveShadow geometry={nodes.M865I432.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M863I431" castShadow receiveShadow geometry={nodes.M863I431.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M861I430" castShadow receiveShadow geometry={nodes.M861I430.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M859I429" castShadow receiveShadow geometry={nodes.M859I429.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M857I428" castShadow receiveShadow geometry={nodes.M857I428.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M855I427" castShadow receiveShadow geometry={nodes.M855I427.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M853I426" castShadow receiveShadow geometry={nodes.M853I426.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M851I425" castShadow receiveShadow geometry={nodes.M851I425.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M849I424" castShadow receiveShadow geometry={nodes.M849I424.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M847I423" castShadow receiveShadow geometry={nodes.M847I423.geometry} material={materials.COL20} position={[2.047, -0.325, -0.918]} />
        <mesh name="M845I422" castShadow receiveShadow geometry={nodes.M845I422.geometry} material={materials.COL18} position={[2.047, -0.325, -0.918]} />
        <mesh name="M843I421" castShadow receiveShadow geometry={nodes.M843I421.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M841I420" castShadow receiveShadow geometry={nodes.M841I420.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M839I419" castShadow receiveShadow geometry={nodes.M839I419.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M837I418" castShadow receiveShadow geometry={nodes.M837I418.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M835I417" castShadow receiveShadow geometry={nodes.M835I417.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M833I416" castShadow receiveShadow geometry={nodes.M833I416.geometry} material={materials.COL20} position={[2.047, -0.325, -0.918]} />
        <mesh name="M831I415" castShadow receiveShadow geometry={nodes.M831I415.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M829I414" castShadow receiveShadow geometry={nodes.M829I414.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M827I413" castShadow receiveShadow geometry={nodes.M827I413.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M825I412" castShadow receiveShadow geometry={nodes.M825I412.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M823I411" castShadow receiveShadow geometry={nodes.M823I411.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M821I410" castShadow receiveShadow geometry={nodes.M821I410.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M819I409" castShadow receiveShadow geometry={nodes.M819I409.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M817I408" castShadow receiveShadow geometry={nodes.M817I408.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M815I407" castShadow receiveShadow geometry={nodes.M815I407.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M813I406" castShadow receiveShadow geometry={nodes.M813I406.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M811I405" castShadow receiveShadow geometry={nodes.M811I405.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M809I404" castShadow receiveShadow geometry={nodes.M809I404.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M807I403" castShadow receiveShadow geometry={nodes.M807I403.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M805I402" castShadow receiveShadow geometry={nodes.M805I402.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M803I401" castShadow receiveShadow geometry={nodes.M803I401.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M801I400" castShadow receiveShadow geometry={nodes.M801I400.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M799I399" castShadow receiveShadow geometry={nodes.M799I399.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M797I398" castShadow receiveShadow geometry={nodes.M797I398.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M795I397" castShadow receiveShadow geometry={nodes.M795I397.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M793I396" castShadow receiveShadow geometry={nodes.M793I396.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M791I395" castShadow receiveShadow geometry={nodes.M791I395.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M789I394" castShadow receiveShadow geometry={nodes.M789I394.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M787I393" castShadow receiveShadow geometry={nodes.M787I393.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M785I392" castShadow receiveShadow geometry={nodes.M785I392.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M783I391" castShadow receiveShadow geometry={nodes.M783I391.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M781I390" castShadow receiveShadow geometry={nodes.M781I390.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M779I389" castShadow receiveShadow geometry={nodes.M779I389.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M777I388" castShadow receiveShadow geometry={nodes.M777I388.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M775I387" castShadow receiveShadow geometry={nodes.M775I387.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M773I386" castShadow receiveShadow geometry={nodes.M773I386.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M771I385" castShadow receiveShadow geometry={nodes.M771I385.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M769I384" castShadow receiveShadow geometry={nodes.M769I384.geometry} material={materials.COL19} position={[2.047, -0.325, -0.918]} />
        <mesh name="M767I383" castShadow receiveShadow geometry={nodes.M767I383.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M765I382" castShadow receiveShadow geometry={nodes.M765I382.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M763I381" castShadow receiveShadow geometry={nodes.M763I381.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M761I380" castShadow receiveShadow geometry={nodes.M761I380.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M759I379" castShadow receiveShadow geometry={nodes.M759I379.geometry} material={materials.COL18} position={[2.047, -0.325, -0.918]} />
        <mesh name="M757I378" castShadow receiveShadow geometry={nodes.M757I378.geometry} material={materials.COL17} position={[2.047, -0.325, -0.918]} />
        <mesh name="M755I377" castShadow receiveShadow geometry={nodes.M755I377.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M753I376" castShadow receiveShadow geometry={nodes.M753I376.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M751I375" castShadow receiveShadow geometry={nodes.M751I375.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M749I374" castShadow receiveShadow geometry={nodes.M749I374.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M747I373" castShadow receiveShadow geometry={nodes.M747I373.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M745I372" castShadow receiveShadow geometry={nodes.M745I372.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M743I371" castShadow receiveShadow geometry={nodes.M743I371.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M741I370" castShadow receiveShadow geometry={nodes.M741I370.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M739I369" castShadow receiveShadow geometry={nodes.M739I369.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M737I368" castShadow receiveShadow geometry={nodes.M737I368.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M735I367" castShadow receiveShadow geometry={nodes.M735I367.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M733I366" castShadow receiveShadow geometry={nodes.M733I366.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M731I365" castShadow receiveShadow geometry={nodes.M731I365.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M729I364" castShadow receiveShadow geometry={nodes.M729I364.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M727I363" castShadow receiveShadow geometry={nodes.M727I363.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M725I362" castShadow receiveShadow geometry={nodes.M725I362.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M723I361" castShadow receiveShadow geometry={nodes.M723I361.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M721I360" castShadow receiveShadow geometry={nodes.M721I360.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M719I359" castShadow receiveShadow geometry={nodes.M719I359.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M717I358" castShadow receiveShadow geometry={nodes.M717I358.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M715I357" castShadow receiveShadow geometry={nodes.M715I357.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M713I356" castShadow receiveShadow geometry={nodes.M713I356.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M711I355" castShadow receiveShadow geometry={nodes.M711I355.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M709I354" castShadow receiveShadow geometry={nodes.M709I354.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M707I353" castShadow receiveShadow geometry={nodes.M707I353.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M705I352" castShadow receiveShadow geometry={nodes.M705I352.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M703I351" castShadow receiveShadow geometry={nodes.M703I351.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M701I350" castShadow receiveShadow geometry={nodes.M701I350.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M699I349" castShadow receiveShadow geometry={nodes.M699I349.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M697I348" castShadow receiveShadow geometry={nodes.M697I348.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M695I347" castShadow receiveShadow geometry={nodes.M695I347.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M693I346" castShadow receiveShadow geometry={nodes.M693I346.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M691I345" castShadow receiveShadow geometry={nodes.M691I345.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M689I344" castShadow receiveShadow geometry={nodes.M689I344.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M687I343" castShadow receiveShadow geometry={nodes.M687I343.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M685I342" castShadow receiveShadow geometry={nodes.M685I342.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M683I341" castShadow receiveShadow geometry={nodes.M683I341.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M681I340" castShadow receiveShadow geometry={nodes.M681I340.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M679I339" castShadow receiveShadow geometry={nodes.M679I339.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M677I338" castShadow receiveShadow geometry={nodes.M677I338.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M675I337" castShadow receiveShadow geometry={nodes.M675I337.geometry} material={materials.COL16} position={[2.047, -0.325, -0.918]} />
        <mesh name="M673I336" castShadow receiveShadow geometry={nodes.M673I336.geometry} material={materials.COL16} position={[2.047, -0.325, -0.918]} />
        <mesh name="M671I335" castShadow receiveShadow geometry={nodes.M671I335.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M669I334" castShadow receiveShadow geometry={nodes.M669I334.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M667I333" castShadow receiveShadow geometry={nodes.M667I333.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M665I332" castShadow receiveShadow geometry={nodes.M665I332.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M663I331" castShadow receiveShadow geometry={nodes.M663I331.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M661I330" castShadow receiveShadow geometry={nodes.M661I330.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M659I329" castShadow receiveShadow geometry={nodes.M659I329.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M657I328" castShadow receiveShadow geometry={nodes.M657I328.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M655I327" castShadow receiveShadow geometry={nodes.M655I327.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M653I326" castShadow receiveShadow geometry={nodes.M653I326.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M651I325" castShadow receiveShadow geometry={nodes.M651I325.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M649I324" castShadow receiveShadow geometry={nodes.M649I324.geometry} material={materials.COL16} position={[2.047, -0.325, -0.918]} />
        <mesh name="M647I323" castShadow receiveShadow geometry={nodes.M647I323.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M645I322" castShadow receiveShadow geometry={nodes.M645I322.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M643I321" castShadow receiveShadow geometry={nodes.M643I321.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M641I320" castShadow receiveShadow geometry={nodes.M641I320.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M639I319" castShadow receiveShadow geometry={nodes.M639I319.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M637I318" castShadow receiveShadow geometry={nodes.M637I318.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M635I317" castShadow receiveShadow geometry={nodes.M635I317.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M633I316" castShadow receiveShadow geometry={nodes.M633I316.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M631I315" castShadow receiveShadow geometry={nodes.M631I315.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M629I314" castShadow receiveShadow geometry={nodes.M629I314.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M627I313" castShadow receiveShadow geometry={nodes.M627I313.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M625I312" castShadow receiveShadow geometry={nodes.M625I312.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M623I311" castShadow receiveShadow geometry={nodes.M623I311.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M621I310" castShadow receiveShadow geometry={nodes.M621I310.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M619I309" castShadow receiveShadow geometry={nodes.M619I309.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M617I308" castShadow receiveShadow geometry={nodes.M617I308.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M615I307" castShadow receiveShadow geometry={nodes.M615I307.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M613I306" castShadow receiveShadow geometry={nodes.M613I306.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M611I305" castShadow receiveShadow geometry={nodes.M611I305.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M609I304" castShadow receiveShadow geometry={nodes.M609I304.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M607I303" castShadow receiveShadow geometry={nodes.M607I303.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M605I302" castShadow receiveShadow geometry={nodes.M605I302.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M603I301" castShadow receiveShadow geometry={nodes.M603I301.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M601I300" castShadow receiveShadow geometry={nodes.M601I300.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M599I299" castShadow receiveShadow geometry={nodes.M599I299.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M597I298" castShadow receiveShadow geometry={nodes.M597I298.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M595I297" castShadow receiveShadow geometry={nodes.M595I297.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M593I296" castShadow receiveShadow geometry={nodes.M593I296.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M591I295" castShadow receiveShadow geometry={nodes.M591I295.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M589I294" castShadow receiveShadow geometry={nodes.M589I294.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M587I293" castShadow receiveShadow geometry={nodes.M587I293.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M585I292" castShadow receiveShadow geometry={nodes.M585I292.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M583I291" castShadow receiveShadow geometry={nodes.M583I291.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M581I290" castShadow receiveShadow geometry={nodes.M581I290.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M579I289" castShadow receiveShadow geometry={nodes.M579I289.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M577I288" castShadow receiveShadow geometry={nodes.M577I288.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M575I287" castShadow receiveShadow geometry={nodes.M575I287.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M573I286" castShadow receiveShadow geometry={nodes.M573I286.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M571I285" castShadow receiveShadow geometry={nodes.M571I285.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M569I284" castShadow receiveShadow geometry={nodes.M569I284.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M567I283" castShadow receiveShadow geometry={nodes.M567I283.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M565I282" castShadow receiveShadow geometry={nodes.M565I282.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M563I281" castShadow receiveShadow geometry={nodes.M563I281.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M561I280" castShadow receiveShadow geometry={nodes.M561I280.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M559I279" castShadow receiveShadow geometry={nodes.M559I279.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M557I278" castShadow receiveShadow geometry={nodes.M557I278.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M555I277" castShadow receiveShadow geometry={nodes.M555I277.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M553I276" castShadow receiveShadow geometry={nodes.M553I276.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M551I275" castShadow receiveShadow geometry={nodes.M551I275.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M549I274" castShadow receiveShadow geometry={nodes.M549I274.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M547I273" castShadow receiveShadow geometry={nodes.M547I273.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M545I272" castShadow receiveShadow geometry={nodes.M545I272.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M543I271" castShadow receiveShadow geometry={nodes.M543I271.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M541I270" castShadow receiveShadow geometry={nodes.M541I270.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M539I269" castShadow receiveShadow geometry={nodes.M539I269.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M537I268" castShadow receiveShadow geometry={nodes.M537I268.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M535I267" castShadow receiveShadow geometry={nodes.M535I267.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M533I266" castShadow receiveShadow geometry={nodes.M533I266.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M531I265" castShadow receiveShadow geometry={nodes.M531I265.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M529I264" castShadow receiveShadow geometry={nodes.M529I264.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M527I263" castShadow receiveShadow geometry={nodes.M527I263.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M525I262" castShadow receiveShadow geometry={nodes.M525I262.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M523I261" castShadow receiveShadow geometry={nodes.M523I261.geometry} material={materials.COL10} position={[2.047, -0.325, -0.918]} />
        <mesh name="M521I260" castShadow receiveShadow geometry={nodes.M521I260.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M519I259" castShadow receiveShadow geometry={nodes.M519I259.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M517I258" castShadow receiveShadow geometry={nodes.M517I258.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M515I257" castShadow receiveShadow geometry={nodes.M515I257.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M513I256" castShadow receiveShadow geometry={nodes.M513I256.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M511I255" castShadow receiveShadow geometry={nodes.M511I255.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M509I254" castShadow receiveShadow geometry={nodes.M509I254.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M507I253" castShadow receiveShadow geometry={nodes.M507I253.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M505I252" castShadow receiveShadow geometry={nodes.M505I252.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M503I251" castShadow receiveShadow geometry={nodes.M503I251.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M501I250" castShadow receiveShadow geometry={nodes.M501I250.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M499I249" castShadow receiveShadow geometry={nodes.M499I249.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M497I248" castShadow receiveShadow geometry={nodes.M497I248.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M495I247" castShadow receiveShadow geometry={nodes.M495I247.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M493I246" castShadow receiveShadow geometry={nodes.M493I246.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M491I245" castShadow receiveShadow geometry={nodes.M491I245.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M489I244" castShadow receiveShadow geometry={nodes.M489I244.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M487I243" castShadow receiveShadow geometry={nodes.M487I243.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M485I242" castShadow receiveShadow geometry={nodes.M485I242.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M483I241" castShadow receiveShadow geometry={nodes.M483I241.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M481I240" castShadow receiveShadow geometry={nodes.M481I240.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M479I239" castShadow receiveShadow geometry={nodes.M479I239.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M477I238" castShadow receiveShadow geometry={nodes.M477I238.geometry} material={materials.COL8} position={[2.047, -0.325, -0.918]} />
        <mesh name="M475I237" castShadow receiveShadow geometry={nodes.M475I237.geometry} material={materials.COL15} position={[2.047, -0.325, -0.918]} />
        <mesh name="M473I236" castShadow receiveShadow geometry={nodes.M473I236.geometry} material={materials.COL15} position={[2.047, -0.325, -0.918]} />
        <mesh name="M471I235" castShadow receiveShadow geometry={nodes.M471I235.geometry} material={materials.COL15} position={[2.047, -0.325, -0.918]} />
        <mesh name="M469I234" castShadow receiveShadow geometry={nodes.M469I234.geometry} material={materials.COL15} position={[2.047, -0.325, -0.918]} />
        <mesh name="M467I233" castShadow receiveShadow geometry={nodes.M467I233.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M465I232" castShadow receiveShadow geometry={nodes.M465I232.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M463I231" castShadow receiveShadow geometry={nodes.M463I231.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M461I230" castShadow receiveShadow geometry={nodes.M461I230.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M459I229" castShadow receiveShadow geometry={nodes.M459I229.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M457I228" castShadow receiveShadow geometry={nodes.M457I228.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M455I227" castShadow receiveShadow geometry={nodes.M455I227.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M453I226" castShadow receiveShadow geometry={nodes.M453I226.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M451I225" castShadow receiveShadow geometry={nodes.M451I225.geometry} material={materials.COL10} position={[2.047, -0.325, -0.918]} />
        <mesh name="M449I224" castShadow receiveShadow geometry={nodes.M449I224.geometry} material={materials.COL10} position={[2.047, -0.325, -0.918]} />
        <mesh name="M447I223" castShadow receiveShadow geometry={nodes.M447I223.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M445I222" castShadow receiveShadow geometry={nodes.M445I222.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M443I221" castShadow receiveShadow geometry={nodes.M443I221.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M441I220" castShadow receiveShadow geometry={nodes.M441I220.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M439I219" castShadow receiveShadow geometry={nodes.M439I219.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M437I218" castShadow receiveShadow geometry={nodes.M437I218.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M435I217" castShadow receiveShadow geometry={nodes.M435I217.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M433I216" castShadow receiveShadow geometry={nodes.M433I216.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M431I215" castShadow receiveShadow geometry={nodes.M431I215.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M429I214" castShadow receiveShadow geometry={nodes.M429I214.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M427I213" castShadow receiveShadow geometry={nodes.M427I213.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M425I212" castShadow receiveShadow geometry={nodes.M425I212.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M423I211" castShadow receiveShadow geometry={nodes.M423I211.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M421I210" castShadow receiveShadow geometry={nodes.M421I210.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M419I209" castShadow receiveShadow geometry={nodes.M419I209.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M417I208" castShadow receiveShadow geometry={nodes.M417I208.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M415I207" castShadow receiveShadow geometry={nodes.M415I207.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M413I206" castShadow receiveShadow geometry={nodes.M413I206.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M411I205" castShadow receiveShadow geometry={nodes.M411I205.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M409I204" castShadow receiveShadow geometry={nodes.M409I204.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M407I203" castShadow receiveShadow geometry={nodes.M407I203.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M405I202" castShadow receiveShadow geometry={nodes.M405I202.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M403I201" castShadow receiveShadow geometry={nodes.M403I201.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M401I200" castShadow receiveShadow geometry={nodes.M401I200.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M399I199" castShadow receiveShadow geometry={nodes.M399I199.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M397I198" castShadow receiveShadow geometry={nodes.M397I198.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M395I197" castShadow receiveShadow geometry={nodes.M395I197.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M393I196" castShadow receiveShadow geometry={nodes.M393I196.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M391I195" castShadow receiveShadow geometry={nodes.M391I195.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M389I194" castShadow receiveShadow geometry={nodes.M389I194.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M387I193" castShadow receiveShadow geometry={nodes.M387I193.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M385I192" castShadow receiveShadow geometry={nodes.M385I192.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M383I191" castShadow receiveShadow geometry={nodes.M383I191.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M381I190" castShadow receiveShadow geometry={nodes.M381I190.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M379I189" castShadow receiveShadow geometry={nodes.M379I189.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M377I188" castShadow receiveShadow geometry={nodes.M377I188.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M375I187" castShadow receiveShadow geometry={nodes.M375I187.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M373I186" castShadow receiveShadow geometry={nodes.M373I186.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M371I185" castShadow receiveShadow geometry={nodes.M371I185.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M369I184" castShadow receiveShadow geometry={nodes.M369I184.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M367I183" castShadow receiveShadow geometry={nodes.M367I183.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M365I182" castShadow receiveShadow geometry={nodes.M365I182.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M363I181" castShadow receiveShadow geometry={nodes.M363I181.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M361I180" castShadow receiveShadow geometry={nodes.M361I180.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M359I179" castShadow receiveShadow geometry={nodes.M359I179.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M357I178" castShadow receiveShadow geometry={nodes.M357I178.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M355I177" castShadow receiveShadow geometry={nodes.M355I177.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M353I176" castShadow receiveShadow geometry={nodes.M353I176.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M351I175" castShadow receiveShadow geometry={nodes.M351I175.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M349I174" castShadow receiveShadow geometry={nodes.M349I174.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M347I173" castShadow receiveShadow geometry={nodes.M347I173.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M345I172" castShadow receiveShadow geometry={nodes.M345I172.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M343I171" castShadow receiveShadow geometry={nodes.M343I171.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M341I170" castShadow receiveShadow geometry={nodes.M341I170.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M339I169" castShadow receiveShadow geometry={nodes.M339I169.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M337I168" castShadow receiveShadow geometry={nodes.M337I168.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M335I167" castShadow receiveShadow geometry={nodes.M335I167.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M333I166" castShadow receiveShadow geometry={nodes.M333I166.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M331I165" castShadow receiveShadow geometry={nodes.M331I165.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M329I164" castShadow receiveShadow geometry={nodes.M329I164.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M327I163" castShadow receiveShadow geometry={nodes.M327I163.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M325I162" castShadow receiveShadow geometry={nodes.M325I162.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M323I161" castShadow receiveShadow geometry={nodes.M323I161.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M321I160" castShadow receiveShadow geometry={nodes.M321I160.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M319I159" castShadow receiveShadow geometry={nodes.M319I159.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M317I158" castShadow receiveShadow geometry={nodes.M317I158.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M315I157" castShadow receiveShadow geometry={nodes.M315I157.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M313I156" castShadow receiveShadow geometry={nodes.M313I156.geometry} material={materials.COL14} position={[2.047, -0.325, -0.918]} />
        <mesh name="M311I155" castShadow receiveShadow geometry={nodes.M311I155.geometry} material={materials.COL14} position={[2.047, -0.325, -0.918]} />
        <mesh name="M309I154" castShadow receiveShadow geometry={nodes.M309I154.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M307I153" castShadow receiveShadow geometry={nodes.M307I153.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M305I152" castShadow receiveShadow geometry={nodes.M305I152.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M303I151" castShadow receiveShadow geometry={nodes.M303I151.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M301I150" castShadow receiveShadow geometry={nodes.M301I150.geometry} material={materials.COL14} position={[2.047, -0.325, -0.918]} />
        <mesh name="M299I149" castShadow receiveShadow geometry={nodes.M299I149.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M297I148" castShadow receiveShadow geometry={nodes.M297I148.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M295I147" castShadow receiveShadow geometry={nodes.M295I147.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M293I146" castShadow receiveShadow geometry={nodes.M293I146.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M291I145" castShadow receiveShadow geometry={nodes.M291I145.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M289I144" castShadow receiveShadow geometry={nodes.M289I144.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M287I143" castShadow receiveShadow geometry={nodes.M287I143.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M285I142" castShadow receiveShadow geometry={nodes.M285I142.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M283I141" castShadow receiveShadow geometry={nodes.M283I141.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M281I140" castShadow receiveShadow geometry={nodes.M281I140.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M279I139" castShadow receiveShadow geometry={nodes.M279I139.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M277I138" castShadow receiveShadow geometry={nodes.M277I138.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M275I137" castShadow receiveShadow geometry={nodes.M275I137.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M273I136" castShadow receiveShadow geometry={nodes.M273I136.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M271I135" castShadow receiveShadow geometry={nodes.M271I135.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M269I134" castShadow receiveShadow geometry={nodes.M269I134.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M267I133" castShadow receiveShadow geometry={nodes.M267I133.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M265I132" castShadow receiveShadow geometry={nodes.M265I132.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M263I131" castShadow receiveShadow geometry={nodes.M263I131.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M261I130" castShadow receiveShadow geometry={nodes.M261I130.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M259I129" castShadow receiveShadow geometry={nodes.M259I129.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M257I128" castShadow receiveShadow geometry={nodes.M257I128.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M255I127" castShadow receiveShadow geometry={nodes.M255I127.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M253I126" castShadow receiveShadow geometry={nodes.M253I126.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M251I125" castShadow receiveShadow geometry={nodes.M251I125.geometry} material={materials.COL13} position={[2.047, -0.325, -0.918]} />
        <mesh name="M249I124" castShadow receiveShadow geometry={nodes.M249I124.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M247I123" castShadow receiveShadow geometry={nodes.M247I123.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M245I122" castShadow receiveShadow geometry={nodes.M245I122.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M243I121" castShadow receiveShadow geometry={nodes.M243I121.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M241I120" castShadow receiveShadow geometry={nodes.M241I120.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M239I119" castShadow receiveShadow geometry={nodes.M239I119.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M237I118" castShadow receiveShadow geometry={nodes.M237I118.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M235I117" castShadow receiveShadow geometry={nodes.M235I117.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M233I116" castShadow receiveShadow geometry={nodes.M233I116.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M231I115" castShadow receiveShadow geometry={nodes.M231I115.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M229I114" castShadow receiveShadow geometry={nodes.M229I114.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M227I113" castShadow receiveShadow geometry={nodes.M227I113.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M225I112" castShadow receiveShadow geometry={nodes.M225I112.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M223I111" castShadow receiveShadow geometry={nodes.M223I111.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M221I110" castShadow receiveShadow geometry={nodes.M221I110.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M219I109" castShadow receiveShadow geometry={nodes.M219I109.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M217I108" castShadow receiveShadow geometry={nodes.M217I108.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M215I107" castShadow receiveShadow geometry={nodes.M215I107.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M213I106" castShadow receiveShadow geometry={nodes.M213I106.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M211I105" castShadow receiveShadow geometry={nodes.M211I105.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M209I104" castShadow receiveShadow geometry={nodes.M209I104.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M207I103" castShadow receiveShadow geometry={nodes.M207I103.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M205I102" castShadow receiveShadow geometry={nodes.M205I102.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M203I101" castShadow receiveShadow geometry={nodes.M203I101.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M201I100" castShadow receiveShadow geometry={nodes.M201I100.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M199I99" castShadow receiveShadow geometry={nodes.M199I99.geometry} material={materials.COL12} position={[2.047, -0.325, -0.918]} />
        <mesh name="M197I98" castShadow receiveShadow geometry={nodes.M197I98.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M195I97" castShadow receiveShadow geometry={nodes.M195I97.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M193I96" castShadow receiveShadow geometry={nodes.M193I96.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M191I95" castShadow receiveShadow geometry={nodes.M191I95.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M189I94" castShadow receiveShadow geometry={nodes.M189I94.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M187I93" castShadow receiveShadow geometry={nodes.M187I93.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M185I92" castShadow receiveShadow geometry={nodes.M185I92.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M183I91" castShadow receiveShadow geometry={nodes.M183I91.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M181I90" castShadow receiveShadow geometry={nodes.M181I90.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M179I89" castShadow receiveShadow geometry={nodes.M179I89.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M177I88" castShadow receiveShadow geometry={nodes.M177I88.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M175I87" castShadow receiveShadow geometry={nodes.M175I87.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M173I86" castShadow receiveShadow geometry={nodes.M173I86.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M171I85" castShadow receiveShadow geometry={nodes.M171I85.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M169I84" castShadow receiveShadow geometry={nodes.M169I84.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M167I83" castShadow receiveShadow geometry={nodes.M167I83.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M165I82" castShadow receiveShadow geometry={nodes.M165I82.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M163I81" castShadow receiveShadow geometry={nodes.M163I81.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M161I80" castShadow receiveShadow geometry={nodes.M161I80.geometry} material={materials.COL11} position={[2.047, -0.325, -0.918]} />
        <mesh name="M159I79" castShadow receiveShadow geometry={nodes.M159I79.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M157I78" castShadow receiveShadow geometry={nodes.M157I78.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M155I77" castShadow receiveShadow geometry={nodes.M155I77.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M153I76" castShadow receiveShadow geometry={nodes.M153I76.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M151I75" castShadow receiveShadow geometry={nodes.M151I75.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M149I74" castShadow receiveShadow geometry={nodes.M149I74.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M147I73" castShadow receiveShadow geometry={nodes.M147I73.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M145I72" castShadow receiveShadow geometry={nodes.M145I72.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M143I71" castShadow receiveShadow geometry={nodes.M143I71.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M141I70" castShadow receiveShadow geometry={nodes.M141I70.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M139I69" castShadow receiveShadow geometry={nodes.M139I69.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M137I68" castShadow receiveShadow geometry={nodes.M137I68.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M135I67" castShadow receiveShadow geometry={nodes.M135I67.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M133I66" castShadow receiveShadow geometry={nodes.M133I66.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M131I65" castShadow receiveShadow geometry={nodes.M131I65.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M129I64" castShadow receiveShadow geometry={nodes.M129I64.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M127I63" castShadow receiveShadow geometry={nodes.M127I63.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M125I62" castShadow receiveShadow geometry={nodes.M125I62.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M123I61" castShadow receiveShadow geometry={nodes.M123I61.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M121I60" castShadow receiveShadow geometry={nodes.M121I60.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M119I59" castShadow receiveShadow geometry={nodes.M119I59.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M117I58" castShadow receiveShadow geometry={nodes.M117I58.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M115I57" castShadow receiveShadow geometry={nodes.M115I57.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M113I56" castShadow receiveShadow geometry={nodes.M113I56.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M111I55" castShadow receiveShadow geometry={nodes.M111I55.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M109I54" castShadow receiveShadow geometry={nodes.M109I54.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M107I53" castShadow receiveShadow geometry={nodes.M107I53.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M105I52" castShadow receiveShadow geometry={nodes.M105I52.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M103I51" castShadow receiveShadow geometry={nodes.M103I51.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M101I50" castShadow receiveShadow geometry={nodes.M101I50.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M99I49" castShadow receiveShadow geometry={nodes.M99I49.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M97I48" castShadow receiveShadow geometry={nodes.M97I48.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M95I47" castShadow receiveShadow geometry={nodes.M95I47.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M93I46" castShadow receiveShadow geometry={nodes.M93I46.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M91I45" castShadow receiveShadow geometry={nodes.M91I45.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M89I44" castShadow receiveShadow geometry={nodes.M89I44.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M87I43" castShadow receiveShadow geometry={nodes.M87I43.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M85I42" castShadow receiveShadow geometry={nodes.M85I42.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M83I41" castShadow receiveShadow geometry={nodes.M83I41.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M81I40" castShadow receiveShadow geometry={nodes.M81I40.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M79I39" castShadow receiveShadow geometry={nodes.M79I39.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M77I38" castShadow receiveShadow geometry={nodes.M77I38.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M75I37" castShadow receiveShadow geometry={nodes.M75I37.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M73I36" castShadow receiveShadow geometry={nodes.M73I36.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M71I35" castShadow receiveShadow geometry={nodes.M71I35.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M69I34" castShadow receiveShadow geometry={nodes.M69I34.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M67I33" castShadow receiveShadow geometry={nodes.M67I33.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M65I32" castShadow receiveShadow geometry={nodes.M65I32.geometry} material={materials.COL10} position={[2.047, -0.325, -0.918]} />
        <mesh name="M63I31" castShadow receiveShadow geometry={nodes.M63I31.geometry} material={materials.COL9} position={[2.047, -0.325, -0.918]} />
        <mesh name="M61I30" castShadow receiveShadow geometry={nodes.M61I30.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M59I29" castShadow receiveShadow geometry={nodes.M59I29.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M57I28" castShadow receiveShadow geometry={nodes.M57I28.geometry} material={materials.COL8} position={[2.047, -0.325, -0.918]} />
        <mesh name="M55I27" castShadow receiveShadow geometry={nodes.M55I27.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M53I26" castShadow receiveShadow geometry={nodes.M53I26.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M51I25" castShadow receiveShadow geometry={nodes.M51I25.geometry} material={materials.COL7} position={[2.047, -0.325, -0.918]} />
        <mesh name="M49I24" castShadow receiveShadow geometry={nodes.M49I24.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M47I23" castShadow receiveShadow geometry={nodes.M47I23.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M45I22" castShadow receiveShadow geometry={nodes.M45I22.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M43I21" castShadow receiveShadow geometry={nodes.M43I21.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M41I20" castShadow receiveShadow geometry={nodes.M41I20.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M39I19" castShadow receiveShadow geometry={nodes.M39I19.geometry} material={materials.COL6} position={[2.047, -0.325, -0.918]} />
        <mesh name="M37I18" castShadow receiveShadow geometry={nodes.M37I18.geometry} material={materials.COL5} position={[2.047, -0.325, -0.918]} />
        <mesh name="M35I17" castShadow receiveShadow geometry={nodes.M35I17.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M33I16" castShadow receiveShadow geometry={nodes.M33I16.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M31I15" castShadow receiveShadow geometry={nodes.M31I15.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M29I14" castShadow receiveShadow geometry={nodes.M29I14.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M27I13" castShadow receiveShadow geometry={nodes.M27I13.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M25I12" castShadow receiveShadow geometry={nodes.M25I12.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M23I11" castShadow receiveShadow geometry={nodes.M23I11.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M21I10" castShadow receiveShadow geometry={nodes.M21I10.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M19I9" castShadow receiveShadow geometry={nodes.M19I9.geometry} material={materials.COL4} position={[2.047, -0.325, -0.918]} />
        <mesh name="M17I8" castShadow receiveShadow geometry={nodes.M17I8.geometry} material={materials.COL3} position={[2.047, -0.325, -0.918]} />
        <mesh name="M15I7" castShadow receiveShadow geometry={nodes.M15I7.geometry} material={materials.COL2} position={[2.047, -0.325, -0.918]} />
        <mesh name="M13I6" castShadow receiveShadow geometry={nodes.M13I6.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M11I5" castShadow receiveShadow geometry={nodes.M11I5.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M9I4" castShadow receiveShadow geometry={nodes.M9I4.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M7I3" castShadow receiveShadow geometry={nodes.M7I3.geometry} material={materials.COL1} position={[2.047, -0.325, -0.918]} />
        <mesh name="M5I2" castShadow receiveShadow geometry={nodes.M5I2.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M3I1" castShadow receiveShadow geometry={nodes.M3I1.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
        <mesh name="M1I0" castShadow receiveShadow geometry={nodes.M1I0.geometry} material={materials.COL0} position={[2.047, -0.325, -0.918]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cnc.glb')
