/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\stock.glb --types --keepnames --keepgroups --shadows --exportdefault 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    M1629I814: THREE.Mesh
    M1627I813: THREE.Mesh
    M1625I812: THREE.Mesh
    M1623I811: THREE.Mesh
    M1621I810: THREE.Mesh
    M1619I809: THREE.Mesh
    M1617I808: THREE.Mesh
    M1615I807: THREE.Mesh
    M1613I806: THREE.Mesh
    M1611I805: THREE.Mesh
    M1609I804: THREE.Mesh
    M1607I803: THREE.Mesh
    M1605I802: THREE.Mesh
    M1603I801: THREE.Mesh
    M1601I800: THREE.Mesh
    M1599I799: THREE.Mesh
    M1597I798: THREE.Mesh
    M1595I797: THREE.Mesh
    M1593I796: THREE.Mesh
    M1591I795: THREE.Mesh
    M1589I794: THREE.Mesh
    M1587I793: THREE.Mesh
    M1585I792: THREE.Mesh
    M1583I791: THREE.Mesh
    M1581I790: THREE.Mesh
    M1579I789: THREE.Mesh
    M1577I788: THREE.Mesh
    M1575I787: THREE.Mesh
    M1573I786: THREE.Mesh
    M1571I785: THREE.Mesh
    M1569I784: THREE.Mesh
    M1567I783: THREE.Mesh
    M1565I782: THREE.Mesh
    M1563I781: THREE.Mesh
    M1561I780: THREE.Mesh
    M1559I779: THREE.Mesh
    M1557I778: THREE.Mesh
    M1555I777: THREE.Mesh
    M1553I776: THREE.Mesh
    M1551I775: THREE.Mesh
    M1549I774: THREE.Mesh
    M1547I773: THREE.Mesh
    M1545I772: THREE.Mesh
    M1543I771: THREE.Mesh
    M1541I770: THREE.Mesh
    M1539I769: THREE.Mesh
    M1537I768: THREE.Mesh
    M1535I767: THREE.Mesh
    M1533I766: THREE.Mesh
    M1531I765: THREE.Mesh
    M1529I764: THREE.Mesh
    M1527I763: THREE.Mesh
    M1525I762: THREE.Mesh
    M1523I761: THREE.Mesh
    M1521I760: THREE.Mesh
    M1519I759: THREE.Mesh
    M1517I758: THREE.Mesh
    M1515I757: THREE.Mesh
    M1513I756: THREE.Mesh
    M1511I755: THREE.Mesh
    M1509I754: THREE.Mesh
    M1507I753: THREE.Mesh
    M1505I752: THREE.Mesh
    M1503I751: THREE.Mesh
    M1501I750: THREE.Mesh
    M1499I749: THREE.Mesh
    M1497I748: THREE.Mesh
    M1495I747: THREE.Mesh
    M1493I746: THREE.Mesh
    M1491I745: THREE.Mesh
    M1489I744: THREE.Mesh
    M1487I743: THREE.Mesh
    M1485I742: THREE.Mesh
    M1483I741: THREE.Mesh
    M1481I740: THREE.Mesh
    M1477I738: THREE.Mesh
    M1475I737: THREE.Mesh
    M1473I736: THREE.Mesh
    M1471I735: THREE.Mesh
    M1469I734: THREE.Mesh
    M1467I733: THREE.Mesh
    M1465I732: THREE.Mesh
    M1463I731: THREE.Mesh
    M1461I730: THREE.Mesh
    M1459I729: THREE.Mesh
    M1457I728: THREE.Mesh
    M1455I727: THREE.Mesh
    M1453I726: THREE.Mesh
    M1451I725: THREE.Mesh
    M1449I724: THREE.Mesh
    M1447I723: THREE.Mesh
    M1445I722: THREE.Mesh
    M1443I721: THREE.Mesh
    M1441I720: THREE.Mesh
    M1439I719: THREE.Mesh
    M1437I718: THREE.Mesh
    M1435I717: THREE.Mesh
    M1433I716: THREE.Mesh
    M1431I715: THREE.Mesh
    M1429I714: THREE.Mesh
    M1427I713: THREE.Mesh
    M1425I712: THREE.Mesh
    M1423I711: THREE.Mesh
    M1421I710: THREE.Mesh
    M1419I709: THREE.Mesh
    M1417I708: THREE.Mesh
    M1415I707: THREE.Mesh
    M1413I706: THREE.Mesh
    M1411I705: THREE.Mesh
    M1409I704: THREE.Mesh
    M1407I703: THREE.Mesh
    M1405I702: THREE.Mesh
    M1403I701: THREE.Mesh
    M1401I700: THREE.Mesh
    M1399I699: THREE.Mesh
    M1397I698: THREE.Mesh
    M1395I697: THREE.Mesh
    M1393I696: THREE.Mesh
    M1391I695: THREE.Mesh
    M1389I694: THREE.Mesh
    M1387I693: THREE.Mesh
    M1385I692: THREE.Mesh
    M1383I691: THREE.Mesh
    M1381I690: THREE.Mesh
    M1379I689: THREE.Mesh
    M1377I688: THREE.Mesh
    M1375I687: THREE.Mesh
    M1373I686: THREE.Mesh
    M1371I685: THREE.Mesh
    M1369I684: THREE.Mesh
    M1367I683: THREE.Mesh
    M1365I682: THREE.Mesh
    M1363I681: THREE.Mesh
    M1361I680: THREE.Mesh
    M1359I679: THREE.Mesh
    M1357I678: THREE.Mesh
    M1355I677: THREE.Mesh
    M1353I676: THREE.Mesh
    M1351I675: THREE.Mesh
    M1349I674: THREE.Mesh
    M1347I673: THREE.Mesh
    M1345I672: THREE.Mesh
    M1343I671: THREE.Mesh
    M1341I670: THREE.Mesh
    M1339I669: THREE.Mesh
    M1337I668: THREE.Mesh
    M1335I667: THREE.Mesh
    M1333I666: THREE.Mesh
    M1331I665: THREE.Mesh
    M1329I664: THREE.Mesh
    M1327I663: THREE.Mesh
    M1325I662: THREE.Mesh
    M1323I661: THREE.Mesh
    M1321I660: THREE.Mesh
    M1319I659: THREE.Mesh
    M1317I658: THREE.Mesh
    M1315I657: THREE.Mesh
    M1313I656: THREE.Mesh
    M1311I655: THREE.Mesh
    M1309I654: THREE.Mesh
    M1307I653: THREE.Mesh
    M1305I652: THREE.Mesh
    M1303I651: THREE.Mesh
    M1301I650: THREE.Mesh
    M1299I649: THREE.Mesh
    M1297I648: THREE.Mesh
    M1295I647: THREE.Mesh
    M1293I646: THREE.Mesh
    M1291I645: THREE.Mesh
    M1289I644: THREE.Mesh
    M1287I643: THREE.Mesh
    M1285I642: THREE.Mesh
    M1283I641: THREE.Mesh
    M1281I640: THREE.Mesh
    M1279I639: THREE.Mesh
    M1277I638: THREE.Mesh
    M1275I637: THREE.Mesh
    M1273I636: THREE.Mesh
    M1271I635: THREE.Mesh
    M1269I634: THREE.Mesh
    M1267I633: THREE.Mesh
    M1265I632: THREE.Mesh
    M1263I631: THREE.Mesh
    M1261I630: THREE.Mesh
    M1259I629: THREE.Mesh
    M1257I628: THREE.Mesh
    M1255I627: THREE.Mesh
    M1253I626: THREE.Mesh
    M1251I625: THREE.Mesh
    M1249I624: THREE.Mesh
    M1247I623: THREE.Mesh
    M1245I622: THREE.Mesh
    M1243I621: THREE.Mesh
    M1241I620: THREE.Mesh
    M1239I619: THREE.Mesh
    M1237I618: THREE.Mesh
    M1235I617: THREE.Mesh
    M1233I616: THREE.Mesh
    M1231I615: THREE.Mesh
    M1229I614: THREE.Mesh
    M1227I613: THREE.Mesh
    M1225I612: THREE.Mesh
    M1223I611: THREE.Mesh
    M1221I610: THREE.Mesh
    M1219I609: THREE.Mesh
    M1217I608: THREE.Mesh
    M1215I607: THREE.Mesh
    M1213I606: THREE.Mesh
    M1211I605: THREE.Mesh
    M1209I604: THREE.Mesh
    M1207I603: THREE.Mesh
    M1205I602: THREE.Mesh
    M1203I601: THREE.Mesh
    M1201I600: THREE.Mesh
    M1199I599: THREE.Mesh
    M1197I598: THREE.Mesh
    M1195I597: THREE.Mesh
    M1193I596: THREE.Mesh
    M1191I595: THREE.Mesh
    M1189I594: THREE.Mesh
    M1187I593: THREE.Mesh
    M1185I592: THREE.Mesh
    M1183I591: THREE.Mesh
    M1181I590: THREE.Mesh
    M1179I589: THREE.Mesh
    M1177I588: THREE.Mesh
    M1175I587: THREE.Mesh
    M1173I586: THREE.Mesh
    M1171I585: THREE.Mesh
    M1169I584: THREE.Mesh
    M1167I583: THREE.Mesh
    M1165I582: THREE.Mesh
    M1163I581: THREE.Mesh
    M1161I580: THREE.Mesh
    M1159I579: THREE.Mesh
    M1157I578: THREE.Mesh
    M1155I577: THREE.Mesh
    M1153I576: THREE.Mesh
    M1151I575: THREE.Mesh
    M1149I574: THREE.Mesh
    M1147I573: THREE.Mesh
    M1145I572: THREE.Mesh
    M1143I571: THREE.Mesh
    M1141I570: THREE.Mesh
    M1139I569: THREE.Mesh
    M1137I568: THREE.Mesh
    M1135I567: THREE.Mesh
    M1133I566: THREE.Mesh
    M1131I565: THREE.Mesh
    M1129I564: THREE.Mesh
    M1127I563: THREE.Mesh
    M1125I562: THREE.Mesh
    M1123I561: THREE.Mesh
    M1121I560: THREE.Mesh
    M1119I559: THREE.Mesh
    M1117I558: THREE.Mesh
    M1115I557: THREE.Mesh
    M1113I556: THREE.Mesh
    M1111I555: THREE.Mesh
    M1109I554: THREE.Mesh
    M1107I553: THREE.Mesh
    M1105I552: THREE.Mesh
    M1103I551: THREE.Mesh
    M1101I550: THREE.Mesh
    M1099I549: THREE.Mesh
    M1097I548: THREE.Mesh
    M1095I547: THREE.Mesh
    M1093I546: THREE.Mesh
    M1091I545: THREE.Mesh
    M1089I544: THREE.Mesh
    M1087I543: THREE.Mesh
    M1085I542: THREE.Mesh
    M1083I541: THREE.Mesh
    M1081I540: THREE.Mesh
    M1079I539: THREE.Mesh
    M1077I538: THREE.Mesh
    M1075I537: THREE.Mesh
    M1073I536: THREE.Mesh
    M1071I535: THREE.Mesh
    M1069I534: THREE.Mesh
    M1067I533: THREE.Mesh
    M1065I532: THREE.Mesh
    M1063I531: THREE.Mesh
    M1061I530: THREE.Mesh
    M1059I529: THREE.Mesh
    M1057I528: THREE.Mesh
    M1055I527: THREE.Mesh
    M1053I526: THREE.Mesh
    M1051I525: THREE.Mesh
    M1049I524: THREE.Mesh
    M1047I523: THREE.Mesh
    M1045I522: THREE.Mesh
    M1043I521: THREE.Mesh
    M1041I520: THREE.Mesh
    M1039I519: THREE.Mesh
    M1037I518: THREE.Mesh
    M1035I517: THREE.Mesh
    M1033I516: THREE.Mesh
    M1031I515: THREE.Mesh
    M1029I514: THREE.Mesh
    M1027I513: THREE.Mesh
    M1025I512: THREE.Mesh
    M1023I511: THREE.Mesh
    M1021I510: THREE.Mesh
    M1019I509: THREE.Mesh
    M1017I508: THREE.Mesh
    M1015I507: THREE.Mesh
    M1013I506: THREE.Mesh
    M1011I505: THREE.Mesh
    M1009I504: THREE.Mesh
    M1007I503: THREE.Mesh
    M1005I502: THREE.Mesh
    M1003I501: THREE.Mesh
    M1001I500: THREE.Mesh
    M999I499: THREE.Mesh
    M997I498: THREE.Mesh
    M995I497: THREE.Mesh
    M993I496: THREE.Mesh
    M991I495: THREE.Mesh
    M989I494: THREE.Mesh
    M987I493: THREE.Mesh
    M985I492: THREE.Mesh
    M983I491: THREE.Mesh
    M981I490: THREE.Mesh
    M979I489: THREE.Mesh
    M977I488: THREE.Mesh
    M975I487: THREE.Mesh
    M973I486: THREE.Mesh
    M971I485: THREE.Mesh
    M969I484: THREE.Mesh
    M967I483: THREE.Mesh
    M965I482: THREE.Mesh
    M963I481: THREE.Mesh
    M961I480: THREE.Mesh
    M959I479: THREE.Mesh
  }
  materials: {
    ['COL0.001']: THREE.MeshStandardMaterial
    ['COL15.001']: THREE.MeshStandardMaterial
    ['COL7.001']: THREE.MeshStandardMaterial
    ['COL6.001']: THREE.MeshStandardMaterial
    ['COL9.001']: THREE.MeshStandardMaterial
    ['COL4.001']: THREE.MeshStandardMaterial
    ['COL12.001']: THREE.MeshStandardMaterial
    COL30: THREE.MeshStandardMaterial
    ['COL5.001']: THREE.MeshStandardMaterial
    ['COL10.001']: THREE.MeshStandardMaterial
    ['COL2.001']: THREE.MeshStandardMaterial
    ['COL11.001']: THREE.MeshStandardMaterial
    COL29: THREE.MeshStandardMaterial
    COL28: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/stock.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="M1629I814" castShadow receiveShadow geometry={nodes.M1629I814.geometry} material={materials['COL0.001']} />
        <mesh name="M1627I813" castShadow receiveShadow geometry={nodes.M1627I813.geometry} material={materials['COL15.001']} />
        <mesh name="M1625I812" castShadow receiveShadow geometry={nodes.M1625I812.geometry} material={materials['COL15.001']} />
        <mesh name="M1623I811" castShadow receiveShadow geometry={nodes.M1623I811.geometry} material={materials['COL15.001']} />
        <mesh name="M1621I810" castShadow receiveShadow geometry={nodes.M1621I810.geometry} material={materials['COL15.001']} />
        <mesh name="M1619I809" castShadow receiveShadow geometry={nodes.M1619I809.geometry} material={materials['COL15.001']} />
        <mesh name="M1617I808" castShadow receiveShadow geometry={nodes.M1617I808.geometry} material={materials['COL15.001']} />
        <mesh name="M1615I807" castShadow receiveShadow geometry={nodes.M1615I807.geometry} material={materials['COL15.001']} />
        <mesh name="M1613I806" castShadow receiveShadow geometry={nodes.M1613I806.geometry} material={materials['COL15.001']} />
        <mesh name="M1611I805" castShadow receiveShadow geometry={nodes.M1611I805.geometry} material={materials['COL15.001']} />
        <mesh name="M1609I804" castShadow receiveShadow geometry={nodes.M1609I804.geometry} material={materials['COL15.001']} />
        <mesh name="M1607I803" castShadow receiveShadow geometry={nodes.M1607I803.geometry} material={materials['COL15.001']} />
        <mesh name="M1605I802" castShadow receiveShadow geometry={nodes.M1605I802.geometry} material={materials['COL15.001']} />
        <mesh name="M1603I801" castShadow receiveShadow geometry={nodes.M1603I801.geometry} material={materials['COL15.001']} />
        <mesh name="M1601I800" castShadow receiveShadow geometry={nodes.M1601I800.geometry} material={materials['COL15.001']} />
        <mesh name="M1599I799" castShadow receiveShadow geometry={nodes.M1599I799.geometry} material={materials['COL15.001']} />
        <mesh name="M1597I798" castShadow receiveShadow geometry={nodes.M1597I798.geometry} material={materials['COL15.001']} />
        <mesh name="M1595I797" castShadow receiveShadow geometry={nodes.M1595I797.geometry} material={materials['COL15.001']} />
        <mesh name="M1593I796" castShadow receiveShadow geometry={nodes.M1593I796.geometry} material={materials['COL15.001']} />
        <mesh name="M1591I795" castShadow receiveShadow geometry={nodes.M1591I795.geometry} material={materials['COL15.001']} />
        <mesh name="M1589I794" castShadow receiveShadow geometry={nodes.M1589I794.geometry} material={materials['COL15.001']} />
        <mesh name="M1587I793" castShadow receiveShadow geometry={nodes.M1587I793.geometry} material={materials['COL7.001']} />
        <mesh name="M1585I792" castShadow receiveShadow geometry={nodes.M1585I792.geometry} material={materials['COL7.001']} />
        <mesh name="M1583I791" castShadow receiveShadow geometry={nodes.M1583I791.geometry} material={materials['COL6.001']} />
        <mesh name="M1581I790" castShadow receiveShadow geometry={nodes.M1581I790.geometry} material={materials['COL9.001']} />
        <mesh name="M1579I789" castShadow receiveShadow geometry={nodes.M1579I789.geometry} material={materials['COL6.001']} />
        <mesh name="M1577I788" castShadow receiveShadow geometry={nodes.M1577I788.geometry} material={materials['COL4.001']} />
        <mesh name="M1575I787" castShadow receiveShadow geometry={nodes.M1575I787.geometry} material={materials['COL12.001']} />
        <mesh name="M1573I786" castShadow receiveShadow geometry={nodes.M1573I786.geometry} material={materials['COL12.001']} />
        <mesh name="M1571I785" castShadow receiveShadow geometry={nodes.M1571I785.geometry} material={materials['COL4.001']} />
        <mesh name="M1569I784" castShadow receiveShadow geometry={nodes.M1569I784.geometry} material={materials['COL12.001']} />
        <mesh name="M1567I783" castShadow receiveShadow geometry={nodes.M1567I783.geometry} material={materials['COL4.001']} />
        <mesh name="M1565I782" castShadow receiveShadow geometry={nodes.M1565I782.geometry} material={materials['COL12.001']} />
        <mesh name="M1563I781" castShadow receiveShadow geometry={nodes.M1563I781.geometry} material={materials['COL4.001']} />
        <mesh name="M1561I780" castShadow receiveShadow geometry={nodes.M1561I780.geometry} material={materials['COL7.001']} />
        <mesh name="M1559I779" castShadow receiveShadow geometry={nodes.M1559I779.geometry} material={materials['COL7.001']} />
        <mesh name="M1557I778" castShadow receiveShadow geometry={nodes.M1557I778.geometry} material={materials['COL7.001']} />
        <mesh name="M1555I777" castShadow receiveShadow geometry={nodes.M1555I777.geometry} material={materials['COL7.001']} />
        <mesh name="M1553I776" castShadow receiveShadow geometry={nodes.M1553I776.geometry} material={materials['COL7.001']} />
        <mesh name="M1551I775" castShadow receiveShadow geometry={nodes.M1551I775.geometry} material={materials['COL7.001']} />
        <mesh name="M1549I774" castShadow receiveShadow geometry={nodes.M1549I774.geometry} material={materials.COL30} />
        <mesh name="M1547I773" castShadow receiveShadow geometry={nodes.M1547I773.geometry} material={materials['COL7.001']} />
        <mesh name="M1545I772" castShadow receiveShadow geometry={nodes.M1545I772.geometry} material={materials['COL5.001']} />
        <mesh name="M1543I771" castShadow receiveShadow geometry={nodes.M1543I771.geometry} material={materials['COL5.001']} />
        <mesh name="M1541I770" castShadow receiveShadow geometry={nodes.M1541I770.geometry} material={materials['COL5.001']} />
        <mesh name="M1539I769" castShadow receiveShadow geometry={nodes.M1539I769.geometry} material={materials['COL7.001']} />
        <mesh name="M1537I768" castShadow receiveShadow geometry={nodes.M1537I768.geometry} material={materials['COL7.001']} />
        <mesh name="M1535I767" castShadow receiveShadow geometry={nodes.M1535I767.geometry} material={materials['COL7.001']} />
        <mesh name="M1533I766" castShadow receiveShadow geometry={nodes.M1533I766.geometry} material={materials['COL7.001']} />
        <mesh name="M1531I765" castShadow receiveShadow geometry={nodes.M1531I765.geometry} material={materials['COL5.001']} />
        <mesh name="M1529I764" castShadow receiveShadow geometry={nodes.M1529I764.geometry} material={materials['COL4.001']} />
        <mesh name="M1527I763" castShadow receiveShadow geometry={nodes.M1527I763.geometry} material={materials['COL10.001']} />
        <mesh name="M1525I762" castShadow receiveShadow geometry={nodes.M1525I762.geometry} material={materials.COL30} />
        <mesh name="M1523I761" castShadow receiveShadow geometry={nodes.M1523I761.geometry} material={materials['COL5.001']} />
        <mesh name="M1521I760" castShadow receiveShadow geometry={nodes.M1521I760.geometry} material={materials['COL5.001']} />
        <mesh name="M1519I759" castShadow receiveShadow geometry={nodes.M1519I759.geometry} material={materials['COL5.001']} />
        <mesh name="M1517I758" castShadow receiveShadow geometry={nodes.M1517I758.geometry} material={materials['COL5.001']} />
        <mesh name="M1515I757" castShadow receiveShadow geometry={nodes.M1515I757.geometry} material={materials['COL5.001']} />
        <mesh name="M1513I756" castShadow receiveShadow geometry={nodes.M1513I756.geometry} material={materials['COL5.001']} />
        <mesh name="M1511I755" castShadow receiveShadow geometry={nodes.M1511I755.geometry} material={materials['COL5.001']} />
        <mesh name="M1509I754" castShadow receiveShadow geometry={nodes.M1509I754.geometry} material={materials['COL5.001']} />
        <mesh name="M1507I753" castShadow receiveShadow geometry={nodes.M1507I753.geometry} material={materials['COL5.001']} />
        <mesh name="M1505I752" castShadow receiveShadow geometry={nodes.M1505I752.geometry} material={materials['COL5.001']} />
        <mesh name="M1503I751" castShadow receiveShadow geometry={nodes.M1503I751.geometry} material={materials['COL5.001']} />
        <mesh name="M1501I750" castShadow receiveShadow geometry={nodes.M1501I750.geometry} material={materials['COL5.001']} />
        <mesh name="M1499I749" castShadow receiveShadow geometry={nodes.M1499I749.geometry} material={materials['COL5.001']} />
        <mesh name="M1497I748" castShadow receiveShadow geometry={nodes.M1497I748.geometry} material={materials['COL5.001']} />
        <mesh name="M1495I747" castShadow receiveShadow geometry={nodes.M1495I747.geometry} material={materials['COL0.001']} />
        <mesh name="M1493I746" castShadow receiveShadow geometry={nodes.M1493I746.geometry} material={materials['COL0.001']} />
        <mesh name="M1491I745" castShadow receiveShadow geometry={nodes.M1491I745.geometry} material={materials['COL7.001']} />
        <mesh name="M1489I744" castShadow receiveShadow geometry={nodes.M1489I744.geometry} material={materials['COL2.001']} />
        <mesh name="M1487I743" castShadow receiveShadow geometry={nodes.M1487I743.geometry} material={materials['COL2.001']} />
        <mesh name="M1485I742" castShadow receiveShadow geometry={nodes.M1485I742.geometry} material={materials['COL2.001']} />
        <mesh name="M1483I741" castShadow receiveShadow geometry={nodes.M1483I741.geometry} material={materials['COL2.001']} />
        <mesh name="M1481I740" castShadow receiveShadow geometry={nodes.M1481I740.geometry} material={materials['COL2.001']} />
        <mesh name="M1477I738" castShadow receiveShadow geometry={nodes.M1477I738.geometry} material={materials['COL2.001']} />
        <mesh name="M1475I737" castShadow receiveShadow geometry={nodes.M1475I737.geometry} material={materials['COL2.001']} />
        <mesh name="M1473I736" castShadow receiveShadow geometry={nodes.M1473I736.geometry} material={materials['COL2.001']} />
        <mesh name="M1471I735" castShadow receiveShadow geometry={nodes.M1471I735.geometry} material={materials['COL2.001']} />
        <mesh name="M1469I734" castShadow receiveShadow geometry={nodes.M1469I734.geometry} material={materials['COL2.001']} />
        <mesh name="M1467I733" castShadow receiveShadow geometry={nodes.M1467I733.geometry} material={materials['COL2.001']} />
        <mesh name="M1465I732" castShadow receiveShadow geometry={nodes.M1465I732.geometry} material={materials['COL2.001']} />
        <mesh name="M1463I731" castShadow receiveShadow geometry={nodes.M1463I731.geometry} material={materials['COL12.001']} />
        <mesh name="M1461I730" castShadow receiveShadow geometry={nodes.M1461I730.geometry} material={materials['COL7.001']} />
        <mesh name="M1459I729" castShadow receiveShadow geometry={nodes.M1459I729.geometry} material={materials['COL11.001']} />
        <mesh name="M1457I728" castShadow receiveShadow geometry={nodes.M1457I728.geometry} material={materials['COL7.001']} />
        <mesh name="M1455I727" castShadow receiveShadow geometry={nodes.M1455I727.geometry} material={materials['COL11.001']} />
        <mesh name="M1453I726" castShadow receiveShadow geometry={nodes.M1453I726.geometry} material={materials['COL7.001']} />
        <mesh name="M1451I725" castShadow receiveShadow geometry={nodes.M1451I725.geometry} material={materials['COL5.001']} />
        <mesh name="M1449I724" castShadow receiveShadow geometry={nodes.M1449I724.geometry} material={materials['COL7.001']} />
        <mesh name="M1447I723" castShadow receiveShadow geometry={nodes.M1447I723.geometry} material={materials['COL7.001']} />
        <mesh name="M1445I722" castShadow receiveShadow geometry={nodes.M1445I722.geometry} material={materials['COL4.001']} />
        <mesh name="M1443I721" castShadow receiveShadow geometry={nodes.M1443I721.geometry} material={materials['COL7.001']} />
        <mesh name="M1441I720" castShadow receiveShadow geometry={nodes.M1441I720.geometry} material={materials['COL6.001']} />
        <mesh name="M1439I719" castShadow receiveShadow geometry={nodes.M1439I719.geometry} material={materials['COL7.001']} />
        <mesh name="M1437I718" castShadow receiveShadow geometry={nodes.M1437I718.geometry} material={materials['COL7.001']} />
        <mesh name="M1435I717" castShadow receiveShadow geometry={nodes.M1435I717.geometry} material={materials['COL7.001']} />
        <mesh name="M1433I716" castShadow receiveShadow geometry={nodes.M1433I716.geometry} material={materials['COL0.001']} />
        <mesh name="M1431I715" castShadow receiveShadow geometry={nodes.M1431I715.geometry} material={materials['COL0.001']} />
        <mesh name="M1429I714" castShadow receiveShadow geometry={nodes.M1429I714.geometry} material={materials['COL5.001']} />
        <mesh name="M1427I713" castShadow receiveShadow geometry={nodes.M1427I713.geometry} material={materials['COL0.001']} />
        <mesh name="M1425I712" castShadow receiveShadow geometry={nodes.M1425I712.geometry} material={materials['COL5.001']} />
        <mesh name="M1423I711" castShadow receiveShadow geometry={nodes.M1423I711.geometry} material={materials['COL7.001']} />
        <mesh name="M1421I710" castShadow receiveShadow geometry={nodes.M1421I710.geometry} material={materials['COL6.001']} />
        <mesh name="M1419I709" castShadow receiveShadow geometry={nodes.M1419I709.geometry} material={materials['COL7.001']} />
        <mesh name="M1417I708" castShadow receiveShadow geometry={nodes.M1417I708.geometry} material={materials['COL5.001']} />
        <mesh name="M1415I707" castShadow receiveShadow geometry={nodes.M1415I707.geometry} material={materials['COL0.001']} />
        <mesh name="M1413I706" castShadow receiveShadow geometry={nodes.M1413I706.geometry} material={materials['COL7.001']} />
        <mesh name="M1411I705" castShadow receiveShadow geometry={nodes.M1411I705.geometry} material={materials['COL7.001']} />
        <mesh name="M1409I704" castShadow receiveShadow geometry={nodes.M1409I704.geometry} material={materials['COL7.001']} />
        <mesh name="M1407I703" castShadow receiveShadow geometry={nodes.M1407I703.geometry} material={materials['COL4.001']} />
        <mesh name="M1405I702" castShadow receiveShadow geometry={nodes.M1405I702.geometry} material={materials['COL7.001']} />
        <mesh name="M1403I701" castShadow receiveShadow geometry={nodes.M1403I701.geometry} material={materials['COL7.001']} />
        <mesh name="M1401I700" castShadow receiveShadow geometry={nodes.M1401I700.geometry} material={materials['COL4.001']} />
        <mesh name="M1399I699" castShadow receiveShadow geometry={nodes.M1399I699.geometry} material={materials['COL7.001']} />
        <mesh name="M1397I698" castShadow receiveShadow geometry={nodes.M1397I698.geometry} material={materials['COL4.001']} />
        <mesh name="M1395I697" castShadow receiveShadow geometry={nodes.M1395I697.geometry} material={materials['COL4.001']} />
        <mesh name="M1393I696" castShadow receiveShadow geometry={nodes.M1393I696.geometry} material={materials['COL10.001']} />
        <mesh name="M1391I695" castShadow receiveShadow geometry={nodes.M1391I695.geometry} material={materials['COL4.001']} />
        <mesh name="M1389I694" castShadow receiveShadow geometry={nodes.M1389I694.geometry} material={materials['COL7.001']} />
        <mesh name="M1387I693" castShadow receiveShadow geometry={nodes.M1387I693.geometry} material={materials['COL7.001']} />
        <mesh name="M1385I692" castShadow receiveShadow geometry={nodes.M1385I692.geometry} material={materials['COL0.001']} />
        <mesh name="M1383I691" castShadow receiveShadow geometry={nodes.M1383I691.geometry} material={materials['COL11.001']} />
        <mesh name="M1381I690" castShadow receiveShadow geometry={nodes.M1381I690.geometry} material={materials['COL11.001']} />
        <mesh name="M1379I689" castShadow receiveShadow geometry={nodes.M1379I689.geometry} material={materials['COL11.001']} />
        <mesh name="M1377I688" castShadow receiveShadow geometry={nodes.M1377I688.geometry} material={materials['COL11.001']} />
        <mesh name="M1375I687" castShadow receiveShadow geometry={nodes.M1375I687.geometry} material={materials['COL7.001']} />
        <mesh name="M1373I686" castShadow receiveShadow geometry={nodes.M1373I686.geometry} material={materials['COL11.001']} />
        <mesh name="M1371I685" castShadow receiveShadow geometry={nodes.M1371I685.geometry} material={materials['COL0.001']} />
        <mesh name="M1369I684" castShadow receiveShadow geometry={nodes.M1369I684.geometry} material={materials['COL11.001']} />
        <mesh name="M1367I683" castShadow receiveShadow geometry={nodes.M1367I683.geometry} material={materials['COL11.001']} />
        <mesh name="M1365I682" castShadow receiveShadow geometry={nodes.M1365I682.geometry} material={materials['COL11.001']} />
        <mesh name="M1363I681" castShadow receiveShadow geometry={nodes.M1363I681.geometry} material={materials['COL11.001']} />
        <mesh name="M1361I680" castShadow receiveShadow geometry={nodes.M1361I680.geometry} material={materials['COL0.001']} />
        <mesh name="M1359I679" castShadow receiveShadow geometry={nodes.M1359I679.geometry} material={materials['COL0.001']} />
        <mesh name="M1357I678" castShadow receiveShadow geometry={nodes.M1357I678.geometry} material={materials['COL0.001']} />
        <mesh name="M1355I677" castShadow receiveShadow geometry={nodes.M1355I677.geometry} material={materials['COL0.001']} />
        <mesh name="M1353I676" castShadow receiveShadow geometry={nodes.M1353I676.geometry} material={materials['COL0.001']} />
        <mesh name="M1351I675" castShadow receiveShadow geometry={nodes.M1351I675.geometry} material={materials['COL0.001']} />
        <mesh name="M1349I674" castShadow receiveShadow geometry={nodes.M1349I674.geometry} material={materials['COL0.001']} />
        <mesh name="M1347I673" castShadow receiveShadow geometry={nodes.M1347I673.geometry} material={materials['COL0.001']} />
        <mesh name="M1345I672" castShadow receiveShadow geometry={nodes.M1345I672.geometry} material={materials['COL0.001']} />
        <mesh name="M1343I671" castShadow receiveShadow geometry={nodes.M1343I671.geometry} material={materials['COL7.001']} />
        <mesh name="M1341I670" castShadow receiveShadow geometry={nodes.M1341I670.geometry} material={materials['COL7.001']} />
        <mesh name="M1339I669" castShadow receiveShadow geometry={nodes.M1339I669.geometry} material={materials['COL0.001']} />
        <mesh name="M1337I668" castShadow receiveShadow geometry={nodes.M1337I668.geometry} material={materials['COL0.001']} />
        <mesh name="M1335I667" castShadow receiveShadow geometry={nodes.M1335I667.geometry} material={materials['COL0.001']} />
        <mesh name="M1333I666" castShadow receiveShadow geometry={nodes.M1333I666.geometry} material={materials['COL0.001']} />
        <mesh name="M1331I665" castShadow receiveShadow geometry={nodes.M1331I665.geometry} material={materials['COL7.001']} />
        <mesh name="M1329I664" castShadow receiveShadow geometry={nodes.M1329I664.geometry} material={materials['COL0.001']} />
        <mesh name="M1327I663" castShadow receiveShadow geometry={nodes.M1327I663.geometry} material={materials['COL0.001']} />
        <mesh name="M1325I662" castShadow receiveShadow geometry={nodes.M1325I662.geometry} material={materials['COL0.001']} />
        <mesh name="M1323I661" castShadow receiveShadow geometry={nodes.M1323I661.geometry} material={materials['COL0.001']} />
        <mesh name="M1321I660" castShadow receiveShadow geometry={nodes.M1321I660.geometry} material={materials['COL0.001']} />
        <mesh name="M1319I659" castShadow receiveShadow geometry={nodes.M1319I659.geometry} material={materials['COL11.001']} />
        <mesh name="M1317I658" castShadow receiveShadow geometry={nodes.M1317I658.geometry} material={materials['COL4.001']} />
        <mesh name="M1315I657" castShadow receiveShadow geometry={nodes.M1315I657.geometry} material={materials['COL7.001']} />
        <mesh name="M1313I656" castShadow receiveShadow geometry={nodes.M1313I656.geometry} material={materials['COL4.001']} />
        <mesh name="M1311I655" castShadow receiveShadow geometry={nodes.M1311I655.geometry} material={materials['COL7.001']} />
        <mesh name="M1309I654" castShadow receiveShadow geometry={nodes.M1309I654.geometry} material={materials['COL7.001']} />
        <mesh name="M1307I653" castShadow receiveShadow geometry={nodes.M1307I653.geometry} material={materials['COL4.001']} />
        <mesh name="M1305I652" castShadow receiveShadow geometry={nodes.M1305I652.geometry} material={materials['COL7.001']} />
        <mesh name="M1303I651" castShadow receiveShadow geometry={nodes.M1303I651.geometry} material={materials['COL4.001']} />
        <mesh name="M1301I650" castShadow receiveShadow geometry={nodes.M1301I650.geometry} material={materials['COL7.001']} />
        <mesh name="M1299I649" castShadow receiveShadow geometry={nodes.M1299I649.geometry} material={materials['COL7.001']} />
        <mesh name="M1297I648" castShadow receiveShadow geometry={nodes.M1297I648.geometry} material={materials['COL4.001']} />
        <mesh name="M1295I647" castShadow receiveShadow geometry={nodes.M1295I647.geometry} material={materials['COL7.001']} />
        <mesh name="M1293I646" castShadow receiveShadow geometry={nodes.M1293I646.geometry} material={materials['COL6.001']} />
        <mesh name="M1291I645" castShadow receiveShadow geometry={nodes.M1291I645.geometry} material={materials['COL7.001']} />
        <mesh name="M1289I644" castShadow receiveShadow geometry={nodes.M1289I644.geometry} material={materials['COL7.001']} />
        <mesh name="M1287I643" castShadow receiveShadow geometry={nodes.M1287I643.geometry} material={materials['COL5.001']} />
        <mesh name="M1285I642" castShadow receiveShadow geometry={nodes.M1285I642.geometry} material={materials['COL7.001']} />
        <mesh name="M1283I641" castShadow receiveShadow geometry={nodes.M1283I641.geometry} material={materials['COL7.001']} />
        <mesh name="M1281I640" castShadow receiveShadow geometry={nodes.M1281I640.geometry} material={materials['COL7.001']} />
        <mesh name="M1279I639" castShadow receiveShadow geometry={nodes.M1279I639.geometry} material={materials['COL7.001']} />
        <mesh name="M1277I638" castShadow receiveShadow geometry={nodes.M1277I638.geometry} material={materials['COL7.001']} />
        <mesh name="M1275I637" castShadow receiveShadow geometry={nodes.M1275I637.geometry} material={materials['COL5.001']} />
        <mesh name="M1273I636" castShadow receiveShadow geometry={nodes.M1273I636.geometry} material={materials['COL0.001']} />
        <mesh name="M1271I635" castShadow receiveShadow geometry={nodes.M1271I635.geometry} material={materials['COL5.001']} />
        <mesh name="M1269I634" castShadow receiveShadow geometry={nodes.M1269I634.geometry} material={materials['COL5.001']} />
        <mesh name="M1267I633" castShadow receiveShadow geometry={nodes.M1267I633.geometry} material={materials['COL0.001']} />
        <mesh name="M1265I632" castShadow receiveShadow geometry={nodes.M1265I632.geometry} material={materials['COL5.001']} />
        <mesh name="M1263I631" castShadow receiveShadow geometry={nodes.M1263I631.geometry} material={materials['COL0.001']} />
        <mesh name="M1261I630" castShadow receiveShadow geometry={nodes.M1261I630.geometry} material={materials['COL0.001']} />
        <mesh name="M1259I629" castShadow receiveShadow geometry={nodes.M1259I629.geometry} material={materials['COL7.001']} />
        <mesh name="M1257I628" castShadow receiveShadow geometry={nodes.M1257I628.geometry} material={materials['COL5.001']} />
        <mesh name="M1255I627" castShadow receiveShadow geometry={nodes.M1255I627.geometry} material={materials['COL4.001']} />
        <mesh name="M1253I626" castShadow receiveShadow geometry={nodes.M1253I626.geometry} material={materials['COL10.001']} />
        <mesh name="M1251I625" castShadow receiveShadow geometry={nodes.M1251I625.geometry} material={materials['COL6.001']} />
        <mesh name="M1249I624" castShadow receiveShadow geometry={nodes.M1249I624.geometry} material={materials['COL7.001']} />
        <mesh name="M1247I623" castShadow receiveShadow geometry={nodes.M1247I623.geometry} material={materials['COL7.001']} />
        <mesh name="M1245I622" castShadow receiveShadow geometry={nodes.M1245I622.geometry} material={materials['COL7.001']} />
        <mesh name="M1243I621" castShadow receiveShadow geometry={nodes.M1243I621.geometry} material={materials['COL7.001']} />
        <mesh name="M1241I620" castShadow receiveShadow geometry={nodes.M1241I620.geometry} material={materials['COL7.001']} />
        <mesh name="M1239I619" castShadow receiveShadow geometry={nodes.M1239I619.geometry} material={materials['COL4.001']} />
        <mesh name="M1237I618" castShadow receiveShadow geometry={nodes.M1237I618.geometry} material={materials['COL7.001']} />
        <mesh name="M1235I617" castShadow receiveShadow geometry={nodes.M1235I617.geometry} material={materials['COL7.001']} />
        <mesh name="M1233I616" castShadow receiveShadow geometry={nodes.M1233I616.geometry} material={materials['COL4.001']} />
        <mesh name="M1231I615" castShadow receiveShadow geometry={nodes.M1231I615.geometry} material={materials['COL7.001']} />
        <mesh name="M1229I614" castShadow receiveShadow geometry={nodes.M1229I614.geometry} material={materials['COL7.001']} />
        <mesh name="M1227I613" castShadow receiveShadow geometry={nodes.M1227I613.geometry} material={materials['COL7.001']} />
        <mesh name="M1225I612" castShadow receiveShadow geometry={nodes.M1225I612.geometry} material={materials['COL4.001']} />
        <mesh name="M1223I611" castShadow receiveShadow geometry={nodes.M1223I611.geometry} material={materials['COL7.001']} />
        <mesh name="M1221I610" castShadow receiveShadow geometry={nodes.M1221I610.geometry} material={materials['COL7.001']} />
        <mesh name="M1219I609" castShadow receiveShadow geometry={nodes.M1219I609.geometry} material={materials['COL4.001']} />
        <mesh name="M1217I608" castShadow receiveShadow geometry={nodes.M1217I608.geometry} material={materials['COL7.001']} />
        <mesh name="M1215I607" castShadow receiveShadow geometry={nodes.M1215I607.geometry} material={materials['COL7.001']} />
        <mesh name="M1213I606" castShadow receiveShadow geometry={nodes.M1213I606.geometry} material={materials['COL7.001']} />
        <mesh name="M1211I605" castShadow receiveShadow geometry={nodes.M1211I605.geometry} material={materials['COL7.001']} />
        <mesh name="M1209I604" castShadow receiveShadow geometry={nodes.M1209I604.geometry} material={materials['COL7.001']} />
        <mesh name="M1207I603" castShadow receiveShadow geometry={nodes.M1207I603.geometry} material={materials['COL7.001']} />
        <mesh name="M1205I602" castShadow receiveShadow geometry={nodes.M1205I602.geometry} material={materials['COL7.001']} />
        <mesh name="M1203I601" castShadow receiveShadow geometry={nodes.M1203I601.geometry} material={materials['COL10.001']} />
        <mesh name="M1201I600" castShadow receiveShadow geometry={nodes.M1201I600.geometry} material={materials['COL4.001']} />
        <mesh name="M1199I599" castShadow receiveShadow geometry={nodes.M1199I599.geometry} material={materials['COL10.001']} />
        <mesh name="M1197I598" castShadow receiveShadow geometry={nodes.M1197I598.geometry} material={materials['COL9.001']} />
        <mesh name="M1195I597" castShadow receiveShadow geometry={nodes.M1195I597.geometry} material={materials['COL6.001']} />
        <mesh name="M1193I596" castShadow receiveShadow geometry={nodes.M1193I596.geometry} material={materials['COL6.001']} />
        <mesh name="M1191I595" castShadow receiveShadow geometry={nodes.M1191I595.geometry} material={materials.COL29} />
        <mesh name="M1189I594" castShadow receiveShadow geometry={nodes.M1189I594.geometry} material={materials['COL4.001']} />
        <mesh name="M1187I593" castShadow receiveShadow geometry={nodes.M1187I593.geometry} material={materials['COL4.001']} />
        <mesh name="M1185I592" castShadow receiveShadow geometry={nodes.M1185I592.geometry} material={materials['COL4.001']} />
        <mesh name="M1183I591" castShadow receiveShadow geometry={nodes.M1183I591.geometry} material={materials.COL28} />
        <mesh name="M1181I590" castShadow receiveShadow geometry={nodes.M1181I590.geometry} material={materials['COL7.001']} />
        <mesh name="M1179I589" castShadow receiveShadow geometry={nodes.M1179I589.geometry} material={materials['COL7.001']} />
        <mesh name="M1177I588" castShadow receiveShadow geometry={nodes.M1177I588.geometry} material={materials['COL12.001']} />
        <mesh name="M1175I587" castShadow receiveShadow geometry={nodes.M1175I587.geometry} material={materials['COL12.001']} />
        <mesh name="M1173I586" castShadow receiveShadow geometry={nodes.M1173I586.geometry} material={materials['COL12.001']} />
        <mesh name="M1171I585" castShadow receiveShadow geometry={nodes.M1171I585.geometry} material={materials['COL12.001']} />
        <mesh name="M1169I584" castShadow receiveShadow geometry={nodes.M1169I584.geometry} material={materials['COL12.001']} />
        <mesh name="M1167I583" castShadow receiveShadow geometry={nodes.M1167I583.geometry} material={materials['COL12.001']} />
        <mesh name="M1165I582" castShadow receiveShadow geometry={nodes.M1165I582.geometry} material={materials['COL12.001']} />
        <mesh name="M1163I581" castShadow receiveShadow geometry={nodes.M1163I581.geometry} material={materials['COL12.001']} />
        <mesh name="M1161I580" castShadow receiveShadow geometry={nodes.M1161I580.geometry} material={materials['COL7.001']} />
        <mesh name="M1159I579" castShadow receiveShadow geometry={nodes.M1159I579.geometry} material={materials['COL4.001']} />
        <mesh name="M1157I578" castShadow receiveShadow geometry={nodes.M1157I578.geometry} material={materials['COL7.001']} />
        <mesh name="M1155I577" castShadow receiveShadow geometry={nodes.M1155I577.geometry} material={materials['COL4.001']} />
        <mesh name="M1153I576" castShadow receiveShadow geometry={nodes.M1153I576.geometry} material={materials['COL7.001']} />
        <mesh name="M1151I575" castShadow receiveShadow geometry={nodes.M1151I575.geometry} material={materials['COL4.001']} />
        <mesh name="M1149I574" castShadow receiveShadow geometry={nodes.M1149I574.geometry} material={materials['COL7.001']} />
        <mesh name="M1147I573" castShadow receiveShadow geometry={nodes.M1147I573.geometry} material={materials['COL4.001']} />
        <mesh name="M1145I572" castShadow receiveShadow geometry={nodes.M1145I572.geometry} material={materials['COL7.001']} />
        <mesh name="M1143I571" castShadow receiveShadow geometry={nodes.M1143I571.geometry} material={materials['COL4.001']} />
        <mesh name="M1141I570" castShadow receiveShadow geometry={nodes.M1141I570.geometry} material={materials['COL4.001']} />
        <mesh name="M1139I569" castShadow receiveShadow geometry={nodes.M1139I569.geometry} material={materials['COL7.001']} />
        <mesh name="M1137I568" castShadow receiveShadow geometry={nodes.M1137I568.geometry} material={materials['COL4.001']} />
        <mesh name="M1135I567" castShadow receiveShadow geometry={nodes.M1135I567.geometry} material={materials['COL7.001']} />
        <mesh name="M1133I566" castShadow receiveShadow geometry={nodes.M1133I566.geometry} material={materials['COL4.001']} />
        <mesh name="M1131I565" castShadow receiveShadow geometry={nodes.M1131I565.geometry} material={materials['COL7.001']} />
        <mesh name="M1129I564" castShadow receiveShadow geometry={nodes.M1129I564.geometry} material={materials['COL4.001']} />
        <mesh name="M1127I563" castShadow receiveShadow geometry={nodes.M1127I563.geometry} material={materials['COL7.001']} />
        <mesh name="M1125I562" castShadow receiveShadow geometry={nodes.M1125I562.geometry} material={materials['COL7.001']} />
        <mesh name="M1123I561" castShadow receiveShadow geometry={nodes.M1123I561.geometry} material={materials['COL4.001']} />
        <mesh name="M1121I560" castShadow receiveShadow geometry={nodes.M1121I560.geometry} material={materials['COL7.001']} />
        <mesh name="M1119I559" castShadow receiveShadow geometry={nodes.M1119I559.geometry} material={materials['COL4.001']} />
        <mesh name="M1117I558" castShadow receiveShadow geometry={nodes.M1117I558.geometry} material={materials['COL7.001']} />
        <mesh name="M1115I557" castShadow receiveShadow geometry={nodes.M1115I557.geometry} material={materials['COL4.001']} />
        <mesh name="M1113I556" castShadow receiveShadow geometry={nodes.M1113I556.geometry} material={materials['COL7.001']} />
        <mesh name="M1111I555" castShadow receiveShadow geometry={nodes.M1111I555.geometry} material={materials['COL4.001']} />
        <mesh name="M1109I554" castShadow receiveShadow geometry={nodes.M1109I554.geometry} material={materials['COL7.001']} />
        <mesh name="M1107I553" castShadow receiveShadow geometry={nodes.M1107I553.geometry} material={materials['COL4.001']} />
        <mesh name="M1105I552" castShadow receiveShadow geometry={nodes.M1105I552.geometry} material={materials['COL4.001']} />
        <mesh name="M1103I551" castShadow receiveShadow geometry={nodes.M1103I551.geometry} material={materials['COL4.001']} />
        <mesh name="M1101I550" castShadow receiveShadow geometry={nodes.M1101I550.geometry} material={materials['COL7.001']} />
        <mesh name="M1099I549" castShadow receiveShadow geometry={nodes.M1099I549.geometry} material={materials['COL4.001']} />
        <mesh name="M1097I548" castShadow receiveShadow geometry={nodes.M1097I548.geometry} material={materials['COL4.001']} />
        <mesh name="M1095I547" castShadow receiveShadow geometry={nodes.M1095I547.geometry} material={materials['COL7.001']} />
        <mesh name="M1093I546" castShadow receiveShadow geometry={nodes.M1093I546.geometry} material={materials['COL4.001']} />
        <mesh name="M1091I545" castShadow receiveShadow geometry={nodes.M1091I545.geometry} material={materials['COL7.001']} />
        <mesh name="M1089I544" castShadow receiveShadow geometry={nodes.M1089I544.geometry} material={materials['COL7.001']} />
        <mesh name="M1087I543" castShadow receiveShadow geometry={nodes.M1087I543.geometry} material={materials['COL4.001']} />
        <mesh name="M1085I542" castShadow receiveShadow geometry={nodes.M1085I542.geometry} material={materials['COL7.001']} />
        <mesh name="M1083I541" castShadow receiveShadow geometry={nodes.M1083I541.geometry} material={materials['COL4.001']} />
        <mesh name="M1081I540" castShadow receiveShadow geometry={nodes.M1081I540.geometry} material={materials['COL7.001']} />
        <mesh name="M1079I539" castShadow receiveShadow geometry={nodes.M1079I539.geometry} material={materials['COL4.001']} />
        <mesh name="M1077I538" castShadow receiveShadow geometry={nodes.M1077I538.geometry} material={materials['COL7.001']} />
        <mesh name="M1075I537" castShadow receiveShadow geometry={nodes.M1075I537.geometry} material={materials['COL4.001']} />
        <mesh name="M1073I536" castShadow receiveShadow geometry={nodes.M1073I536.geometry} material={materials['COL7.001']} />
        <mesh name="M1071I535" castShadow receiveShadow geometry={nodes.M1071I535.geometry} material={materials['COL4.001']} />
        <mesh name="M1069I534" castShadow receiveShadow geometry={nodes.M1069I534.geometry} material={materials['COL7.001']} />
        <mesh name="M1067I533" castShadow receiveShadow geometry={nodes.M1067I533.geometry} material={materials['COL4.001']} />
        <mesh name="M1065I532" castShadow receiveShadow geometry={nodes.M1065I532.geometry} material={materials['COL4.001']} />
        <mesh name="M1063I531" castShadow receiveShadow geometry={nodes.M1063I531.geometry} material={materials['COL7.001']} />
        <mesh name="M1061I530" castShadow receiveShadow geometry={nodes.M1061I530.geometry} material={materials['COL4.001']} />
        <mesh name="M1059I529" castShadow receiveShadow geometry={nodes.M1059I529.geometry} material={materials['COL7.001']} />
        <mesh name="M1057I528" castShadow receiveShadow geometry={nodes.M1057I528.geometry} material={materials['COL4.001']} />
        <mesh name="M1055I527" castShadow receiveShadow geometry={nodes.M1055I527.geometry} material={materials['COL7.001']} />
        <mesh name="M1053I526" castShadow receiveShadow geometry={nodes.M1053I526.geometry} material={materials['COL4.001']} />
        <mesh name="M1051I525" castShadow receiveShadow geometry={nodes.M1051I525.geometry} material={materials['COL7.001']} />
        <mesh name="M1049I524" castShadow receiveShadow geometry={nodes.M1049I524.geometry} material={materials['COL7.001']} />
        <mesh name="M1047I523" castShadow receiveShadow geometry={nodes.M1047I523.geometry} material={materials['COL4.001']} />
        <mesh name="M1045I522" castShadow receiveShadow geometry={nodes.M1045I522.geometry} material={materials['COL4.001']} />
        <mesh name="M1043I521" castShadow receiveShadow geometry={nodes.M1043I521.geometry} material={materials['COL7.001']} />
        <mesh name="M1041I520" castShadow receiveShadow geometry={nodes.M1041I520.geometry} material={materials['COL4.001']} />
        <mesh name="M1039I519" castShadow receiveShadow geometry={nodes.M1039I519.geometry} material={materials['COL7.001']} />
        <mesh name="M1037I518" castShadow receiveShadow geometry={nodes.M1037I518.geometry} material={materials['COL4.001']} />
        <mesh name="M1035I517" castShadow receiveShadow geometry={nodes.M1035I517.geometry} material={materials['COL7.001']} />
        <mesh name="M1033I516" castShadow receiveShadow geometry={nodes.M1033I516.geometry} material={materials['COL4.001']} />
        <mesh name="M1031I515" castShadow receiveShadow geometry={nodes.M1031I515.geometry} material={materials['COL7.001']} />
        <mesh name="M1029I514" castShadow receiveShadow geometry={nodes.M1029I514.geometry} material={materials['COL7.001']} />
        <mesh name="M1027I513" castShadow receiveShadow geometry={nodes.M1027I513.geometry} material={materials['COL4.001']} />
        <mesh name="M1025I512" castShadow receiveShadow geometry={nodes.M1025I512.geometry} material={materials['COL7.001']} />
        <mesh name="M1023I511" castShadow receiveShadow geometry={nodes.M1023I511.geometry} material={materials['COL4.001']} />
        <mesh name="M1021I510" castShadow receiveShadow geometry={nodes.M1021I510.geometry} material={materials['COL7.001']} />
        <mesh name="M1019I509" castShadow receiveShadow geometry={nodes.M1019I509.geometry} material={materials['COL4.001']} />
        <mesh name="M1017I508" castShadow receiveShadow geometry={nodes.M1017I508.geometry} material={materials['COL7.001']} />
        <mesh name="M1015I507" castShadow receiveShadow geometry={nodes.M1015I507.geometry} material={materials['COL4.001']} />
        <mesh name="M1013I506" castShadow receiveShadow geometry={nodes.M1013I506.geometry} material={materials['COL7.001']} />
        <mesh name="M1011I505" castShadow receiveShadow geometry={nodes.M1011I505.geometry} material={materials['COL4.001']} />
        <mesh name="M1009I504" castShadow receiveShadow geometry={nodes.M1009I504.geometry} material={materials['COL4.001']} />
        <mesh name="M1007I503" castShadow receiveShadow geometry={nodes.M1007I503.geometry} material={materials['COL7.001']} />
        <mesh name="M1005I502" castShadow receiveShadow geometry={nodes.M1005I502.geometry} material={materials['COL11.001']} />
        <mesh name="M1003I501" castShadow receiveShadow geometry={nodes.M1003I501.geometry} material={materials['COL11.001']} />
        <mesh name="M1001I500" castShadow receiveShadow geometry={nodes.M1001I500.geometry} material={materials['COL7.001']} />
        <mesh name="M999I499" castShadow receiveShadow geometry={nodes.M999I499.geometry} material={materials['COL0.001']} />
        <mesh name="M997I498" castShadow receiveShadow geometry={nodes.M997I498.geometry} material={materials['COL7.001']} />
        <mesh name="M995I497" castShadow receiveShadow geometry={nodes.M995I497.geometry} material={materials['COL7.001']} />
        <mesh name="M993I496" castShadow receiveShadow geometry={nodes.M993I496.geometry} material={materials['COL7.001']} />
        <mesh name="M991I495" castShadow receiveShadow geometry={nodes.M991I495.geometry} material={materials['COL7.001']} />
        <mesh name="M989I494" castShadow receiveShadow geometry={nodes.M989I494.geometry} material={materials['COL7.001']} />
        <mesh name="M987I493" castShadow receiveShadow geometry={nodes.M987I493.geometry} material={materials['COL7.001']} />
        <mesh name="M985I492" castShadow receiveShadow geometry={nodes.M985I492.geometry} material={materials['COL7.001']} />
        <mesh name="M983I491" castShadow receiveShadow geometry={nodes.M983I491.geometry} material={materials['COL7.001']} />
        <mesh name="M981I490" castShadow receiveShadow geometry={nodes.M981I490.geometry} material={materials['COL0.001']} />
        <mesh name="M979I489" castShadow receiveShadow geometry={nodes.M979I489.geometry} material={materials['COL7.001']} />
        <mesh name="M977I488" castShadow receiveShadow geometry={nodes.M977I488.geometry} material={materials['COL12.001']} />
        <mesh name="M975I487" castShadow receiveShadow geometry={nodes.M975I487.geometry} material={materials['COL12.001']} />
        <mesh name="M973I486" castShadow receiveShadow geometry={nodes.M973I486.geometry} material={materials['COL12.001']} />
        <mesh name="M971I485" castShadow receiveShadow geometry={nodes.M971I485.geometry} material={materials['COL12.001']} />
        <mesh name="M969I484" castShadow receiveShadow geometry={nodes.M969I484.geometry} material={materials['COL12.001']} />
        <mesh name="M967I483" castShadow receiveShadow geometry={nodes.M967I483.geometry} material={materials['COL12.001']} />
        <mesh name="M965I482" castShadow receiveShadow geometry={nodes.M965I482.geometry} material={materials['COL12.001']} />
        <mesh name="M963I481" castShadow receiveShadow geometry={nodes.M963I481.geometry} material={materials['COL12.001']} />
        <mesh name="M961I480" castShadow receiveShadow geometry={nodes.M961I480.geometry} material={materials['COL12.001']} />
        <mesh name="M959I479" castShadow receiveShadow geometry={nodes.M959I479.geometry} material={materials['COL12.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/stock.glb')
